### PR TITLE
Address the issue #2407

### LINKED ISSUE #2407: Adding check and warning message for defaultThermalExpansionCoefficient
**What is the requested feature?**
Currently, `defaultThermalExpansionCoefficient` needs to be defined separately in both the solid model and the `BiotPorosity` model for THM simulations. Different formulas might be used in different sections within the same xml file by end users. Sanity check is missing to protect GEOS from inconsistent or incomplete input.

**Is your request related to a specific problem?**
For this [tutorial example](https://geosx-geosx.readthedocs-hosted.com/en/latest/docs/sphinx/advancedExamples/validationStudies/wellboreProblems/thermoPoroElasticWellbore/Example.html), if `defaultThermalExpansionCoefficient` is missing in the `BiotPorosity` model, simulation results deviate away from the corresponding analytical solution.
image

**Describe the solution you'd like**
Sanity check and warning message are expected for `defaultThermalExpansionCoefficient` and related theory of `BiotPorosity` model should also be updated.

### PR DESCRIPTION
**Pull request by sytuannguyen**
There are two different Thermal Expansion Coefficients (TEC), one for updating stress/strain and one for updating the porosity w.r.t temperature change. Actually a same name is used for these two TEC in the input XML interface. 

This PR aims to specify two different name for these two differnt parameters to avoid potential user confusion as shown in the issue #2407 .

Rebaseline: https://github.com/GEOS-DEV/integratedTests/pull/70

### CODE REVIEW

**Comment by sytuannguyen** [comment]
This PR does not require rebaseline because it modifies only the parameters' names, not their values.

**Comment by paveltomin** [comment]
> This PR does not require rebaseline because it modifies only the parameters' names, not their values.

You sure?

**Comment by klevzoff** [comment]
Attribute/wrapper names become hdf5 group names, so there will be a diff in the structure

**Comment by sytuannguyen** [comment]
@paveltomin @klevzoff Thank you!

**Review by jhuang2601 — APPROVED** [review]
Looks good!

**Comment by jhuang2601** [comment]
This PR went through `ci: run integrated tests` and requires rebaseline
```
    Status     : TestCase                                                    : Directory                                                                          : Elapsed : Resources : TestStep  
    ---------- : ----------------------------------------------------------- : ---------------------------------------------------------------------------------- : ------- : --------- : ----------
    FAIL CHECK : PoroElastic_staircase_singlephase_3d_sequential_01          : poroElasticCoupling/PoroElastic_staircase_singlephase_3d_sequential_01             : 0:00:18 : 0:00:18   : restartcheck
    FAIL CHECK : DeviatedPoroElasticWellbore_Injection_01                    : wellboreMesh/DeviatedPoroElasticWellbore_Injection_01                              : 0:00:07 : 0:00:07   : restartcheck
    FAIL CHECK : SSLE-sedov_01                                               : solidMechanicsSSLE/SSLE-sedov_01                                                   : 0:00:06 : 0:00:06   : restartcheck
    FAIL CHECK : DeviatedElastic_Wellbore_01                                 : wellboreMesh/DeviatedElastic_Wellbore_01                                           : 0:00:03 : 0:00:03   : restartcheck
    FAIL CHECK : pennyShapedToughnessDominated_poroelastic_01                : HydrofracturingSolver/pennyShapedToughnessDominated_poroelastic_01                 : 0:00:09 : 0:00:09   : restartcheck
    FAIL CHECK : ExponentialDecayPermeability_edfm_01                        : poromechanicsFractures/ExponentialDecayPermeability_edfm_01                        : 0:00:14 : 0:00:14   : restartcheck
    FAIL CHECK : DryFrac_ThreeNodesPinched_SlantFrac_01                      : SurfaceGenerator/DryFrac_ThreeNodesPinched_SlantFrac_01                            : 0:00:04 : 0:00:04   : restartcheck
    FAIL CHECK : ThermoPoroElastic_consolidation_sequential_01               : thermoPoromechanics/ThermoPoroElastic_consolidation_sequential_01                  : 0:00:12 : 0:00:12   : restartcheck
    FAIL CHECK : PoroElastic_efem-edfm_verticalFrac_smoke_01                 : poromechanicsFractures/PoroElastic_efem-edfm_verticalFrac_smoke_01                 : 0:00:05 : 0:00:05   : restartcheck
    FAIL CHECK : ThermoPoroElastic_efem-edfm_verticalFrac_01                 : thermoPoromechanicsFractures/ThermoPoroElastic_efem-edfm_verticalFrac_01           : 0:00:05 : 0:00:05   : restartcheck
    FAIL CHECK : PoroElastic_Wellbore_smoke_01                               : poroElasticCoupling/PoroElastic_Wellbore_smoke_01                                  : 0:00:05 : 0:00:05   : restartcheck
    FAIL CHECK : PhaseFieldFracture_Nucleation_smoke_01                      : phaseFieldFracture/PhaseFieldFracture_Nucleation_smoke_01                          : 0:00:26 : 0:00:26   : restartcheck
    FAIL CHECK : PhaseFieldFracture_CohesiveModel_01                         : phaseFieldFracture/PhaseFieldFracture_CohesiveModel_01                             : 0:00:05 : 0:00:05   : restartcheck
    FAIL CHECK : PoroElastic_gravity_02                                      : poroElasticCoupling/PoroElastic_gravity_02                                         : 0:00:02 : 0:00:04   : restartcheck
    FAIL CHECK : ExponentialDecayPermeability_conformingFracture_01          : poromechanicsFractures/ExponentialDecayPermeability_conformingFracture_01          : 0:00:10 : 0:00:10   : restartcheck
    FAIL CHECK : kgdNodeBased_C3D6_smoke_01                                  : HydrofracturingSolver/kgdNodeBased_C3D6_smoke_01                                   : 0:00:29 : 0:00:29   : restartcheck
    FAIL CHECK : PoroElastic_Mandel_smoke_sequential_01                      : poroElasticCoupling/PoroElastic_Mandel_smoke_sequential_01                         : 0:00:05 : 0:00:05   : restartcheck
    FAIL CHECK : ThermoPoroElastic_consolidation_fim_01                      : thermoPoromechanics/ThermoPoroElastic_consolidation_fim_01                         : 0:00:10 : 0:00:10   : restartcheck
    FAIL CHECK : PoroElastic_deadoil_3ph_baker_2d_sequential_01              : poroElasticCoupling/PoroElastic_deadoil_3ph_baker_2d_sequential_01                 : 0:00:12 : 0:00:12   : restartcheck
    FAIL CHECK : DeviatedPoroElasticWellbore_Drilling_01                     : wellboreMesh/DeviatedPoroElasticWellbore_Drilling_01                               : 0:00:07 : 0:00:07   : restartcheck
    FAIL CHECK : PoroElastic_efem-edfm_pressurizedFrac_smoke_01              : poromechanicsFractures/PoroElastic_efem-edfm_pressurizedFrac_smoke_01              : 0:00:04 : 0:00:04   : restartcheck
    FAIL CHECK : Sneddon_contactMechanics_01                                 : contactMechanics/Sneddon_contactMechanics_01                                       : 0:00:04 : 0:00:04   : restartcheck
    FAIL CHECK : SneddonRotated_smoke_01                                     : embeddedFractures/SneddonRotated_smoke_01                                          : 0:00:03 : 0:00:03   : restartcheck
    FAIL CHECK : PoroModifiedCamClay_Wellbore_smoke_01                       : poroElasticCoupling/PoroModifiedCamClay_Wellbore_smoke_01                          : 0:00:05 : 0:00:05   : restartcheck
    FAIL CHECK : CasedThermoElasticWellbore_smoke_01                         : thermoPoromechanics/CasedThermoElasticWellbore_smoke_01                            : 0:00:06 : 0:00:06   : restartcheck
    FAIL CHECK : ThermoPoroElastic_consolidation_sequential_02               : thermoPoromechanics/ThermoPoroElastic_consolidation_sequential_02                  : 0:00:08 : 0:00:16   : restartcheck
    FAIL CHECK : walshQuarterNoChombo_smoke_01                               : HydrofracturingSolver/walshQuarterNoChombo_smoke_01                                : 0:00:22 : 0:00:22   : restartcheck
    FAIL CHECK : kgdViscosityDominated_smoke_01                              : HydrofracturingSolver/kgdViscosityDominated_smoke_01                               : 0:00:57 : 0:00:57   : restartcheck
    FAIL CHECK : PoroElastic_efem-edfm_inclinedFrac_smoke_01                 : poromechanicsFractures/PoroElastic_efem-edfm_inclinedFrac_smoke_01                 : 0:00:04 : 0:00:04   : restartcheck
    FAIL CHECK : ThermoPoroElasticWellbore_smoke_01                          : wellboreMesh/ThermoPoroElasticWellbore_smoke_01                                    : 0:00:03 : 0:00:03   : restartcheck
    FAIL CHECK : PhaseFieldFracture_CohesiveModel_02                         : phaseFieldFracture/PhaseFieldFracture_CohesiveModel_02                             : 0:00:04 : 0:00:08   : restartcheck
    FAIL CHECK : PoroElastic_gravity_01                                      : poroElasticCoupling/PoroElastic_gravity_01                                         : 0:00:04 : 0:00:04   : restartcheck
    FAIL CHECK : KirschProblem_01                                            : wellboreMesh/KirschProblem_01                                                      : 0:00:03 : 0:00:03   : restartcheck
    FAIL CHECK : PoroElastic_conformingFracture_2d_openingFrac_vertical_01   : poromechanicsFractures/PoroElastic_conformingFracture_2d_openingFrac_vertical_01   : 0:00:05 : 0:00:05   : restartcheck
    FAIL CHECK : gravity_02                                                  : solidMechanicsSSLE/gravity_02                                                      : 0:00:02 : 0:00:04   : restartcheck
    FAIL CHECK : gravity_01                                                  : solidMechanicsSSLE/gravity_01                                                      : 0:00:03 : 0:00:03   : restartcheck
    FAIL CHECK : elasticHollowCylinder_isotropic_smoke_01                    : solidMechanicsSSLE/elasticHollowCylinder_isotropic_smoke_01                        : 0:00:03 : 0:00:03   : restartcheck
    FAIL CHECK : elasticHollowCylinder_transverseIsotropic_smoke_01          : solidMechanicsSSLE/elasticHollowCylinder_transverseIsotropic_smoke_01              : 0:00:03 : 0:00:03   : restartcheck
    FAIL CHECK : PhaseFieldFracture_DamageOnly_01                            : phaseFieldFracture/PhaseFieldFracture_DamageOnly_01                                : 0:00:04 : 0:00:04   : restartcheck
    FAIL CHECK : kgdToughnessDominated_smoke_01                              : HydrofracturingSolver/kgdToughnessDominated_smoke_01                               : 0:00:32 : 0:00:32   : restartcheck
    FAIL CHECK : pennyShapedViscosityDominated_poroelastic_01                : HydrofracturingSolver/pennyShapedViscosityDominated_poroelastic_01                 : 0:00:11 : 0:00:11   : restartcheck
    FAIL CHECK : PoroElastic_Terzaghi_FIM_01                                 : poroElasticCoupling/PoroElastic_Terzaghi_FIM_01                                    : 0:00:07 : 0:00:07   : restartcheck
    FAIL CHECK : PoroElastic_staircase_singlephase_3d_fim_01                 : poroElasticCoupling/PoroElastic_staircase_singlephase_3d_fim_01                    : 0:00:13 : 0:00:13   : restartcheck
    FAIL CHECK : DruckerPrager_Wellbore_01                                   : wellboreMesh/DruckerPrager_Wellbore_01                                             : 0:00:03 : 0:00:03   : restartcheck
    FAIL CHECK : PoroElastic_staircase_co2_3d_sequential_01                  : poroElasticCoupling/PoroElastic_staircase_co2_3d_sequential_01                     : 0:00:53 : 0:00:53   : restartcheck
    FAIL CHECK : ContactMechanics_TFrac_01                                   : contactMechanics/ContactMechanics_TFrac_01                                         : 0:00:08 : 0:00:08   : restartcheck
    FAIL CHECK : ThermoPoroElastic_staircase_co2_smoke_01                    : thermoPoromechanics/ThermoPoroElastic_staircase_co2_smoke_01                       : 0:00:43 : 0:00:43   : restartcheck
    FAIL CHECK : PoroDelftEgg_Wellbore_smoke_01                              : poroElasticCoupling/PoroDelftEgg_Wellbore_smoke_01                                 : 0:00:05 : 0:00:05   : restartcheck
    FAIL CHECK : PoroElastic_conformingFracture_2d_openingFrac_horizontal_01 : poromechanicsFractures/PoroElastic_conformingFracture_2d_openingFrac_horizontal_01 : 0:00:05 : 0:00:05   : restartcheck
    FAIL CHECK : PoroElastic_Mandel_smoke_fim_01                             : poroElasticCoupling/PoroElastic_Mandel_smoke_fim_01                                : 0:00:05 : 0:00:05   : restartcheck
    FAIL CHECK : kgdViscosityDominated_poroelastic_01                        : HydrofracturingSolver/kgdViscosityDominated_poroelastic_01                         : 0:00:06 : 0:00:06   : restartcheck
    FAIL CHECK : DryFrac_ThreeNodesPinched_HorizontalFrac_01                 : SurfaceGenerator/DryFrac_ThreeNodesPinched_HorizontalFrac_01                       : 0:00:04 : 0:00:04   : restartcheck
    FAIL CHECK : PhaseFieldFracture_SpectralSplit_01                         : phaseFieldFracture/PhaseFieldFracture_SpectralSplit_01                             : 0:00:09 : 0:00:09   : restartcheck
    FAIL CHECK : pknViscosityDominated_smoke_01                              : HydrofracturingSolver/pknViscosityDominated_smoke_01                               : 0:23:22 : 0:23:22   : restartcheck
    FAIL CHECK : CasedElastic_Wellbore_01                                    : wellboreMesh/CasedElastic_Wellbore_01                                              : 0:00:04 : 0:00:04   : restartcheck
    FAIL CHECK : Sneddon_embeddedFrac_smoke_01                               : embeddedFractures/Sneddon_embeddedFrac_smoke_01                                    : 0:00:03 : 0:00:03   : restartcheck
    FAIL CHECK : relaxationTest_01                                           : viscoPlastic/relaxationTest_01                                                     : 0:00:05 : 0:00:05   : restartcheck
    FAIL CHECK : elasticHollowCylinder_orthotropic_smoke_01                  : solidMechanicsSSLE/elasticHollowCylinder_orthotropic_smoke_01                      : 0:00:03 : 0:00:03   : restartcheck
    FAIL CHECK : DryFrac_StaticPenny_PrismElem_01                            : SurfaceGenerator/DryFrac_StaticPenny_PrismElem_01                                  : 0:00:16 : 0:00:16   : restartcheck
    FAIL CHECK : heterogeneousInSitu_smoke_01                                : HydrofracturingSolver/heterogeneousInSitu_smoke_01                                 : 0:00:08 : 0:00:08   : restartcheck
    FAIL CHECK : PoroElastic_hybridHexPrism_co2_fim_3d_01                    : poroElasticCoupling/PoroElastic_hybridHexPrism_co2_fim_3d_01                       : 0:08:20 : 0:08:20   : restartcheck
    FAIL CHECK : plasticCubeReset_02                                         : solidMechanicsSSLE/plasticCubeReset_02                                             : 0:00:02 : 0:00:04   : restartcheck
    FAIL CHECK : PoroElastic_deadoil_3ph_baker_2d_fim_01                     : poroElasticCoupling/PoroElastic_deadoil_3ph_baker_2d_fim_01                        : 0:00:10 : 0:00:10   : restartcheck
    FAIL CHECK : PoroElastic_permeableFault_smoke_01                         : poroElasticCoupling/PoroElastic_permeableFault_smoke_01                            : 0:00:04 : 0:00:04   : restartcheck
    FAIL CHECK : pennyShapedToughnessDominated_smoke_01                      : HydrofracturingSolver/pennyShapedToughnessDominated_smoke_01                       : 0:18:28 : 0:18:28   : restartcheck
    FAIL CHECK : beamBending_hybridHexPrism_smoke_01                         : solidMechanicsSSLE/beamBending_hybridHexPrism_smoke_01                             : 0:00:04 : 0:00:04   : restartcheck
    FAIL CHECK : ContactMechanics_UnstructuredCrack_01                       : contactMechanics/ContactMechanics_UnstructuredCrack_01                             : 0:00:08 : 0:00:08   : restartcheck
    FAIL CHECK : ModifiedCamClay_Wellbore_01                                 : wellboreMesh/ModifiedCamClay_Wellbore_01                                           : 0:00:03 : 0:00:03   : restartcheck
    FAIL CHECK : Sneddon_embeddedFrac_staticCondensation_smoke_01            : embeddedFractures/Sneddon_embeddedFrac_staticCondensation_smoke_01                 : 0:00:03 : 0:00:03   : restartcheck
    FAIL CHECK : WillisRichardsPermeability_EDFM_01                          : poromechanicsFractures/WillisRichardsPermeability_EDFM_01                          : 0:00:15 : 0:00:15   : restartcheck
    FAIL CHECK : ExtendedDruckerPrager_Wellbore_01                           : wellboreMesh/ExtendedDruckerPrager_Wellbore_01                                     : 0:00:03 : 0:00:03   : restartcheck
    FAIL CHECK : CasedElasticWellbore_ImperfectInterfaces_smoke_01           : wellboreMesh/CasedElasticWellbore_ImperfectInterfaces_smoke_01                     : 0:00:04 : 0:00:04   : restartcheck
    FAIL CHECK : beamBending_01                                              : solidMechanicsSSLE/beamBending_01                                                  : 0:00:11 : 0:00:11   : restartcheck
    FAIL CHECK : PoroDruckerPrager_Wellbore_smoke_01                         : poroElasticCoupling/PoroDruckerPrager_Wellbore_smoke_01                            : 0:00:05 : 0:00:05   : restartcheck
    FAIL CHECK : plasticCubeReset_01                                         : solidMechanicsSSLE/plasticCubeReset_01                                             : 0:00:04 : 0:00:04   : restartcheck
    FAIL CHECK : EmbFrac_Compression_CoulombFriction_01                      : embeddedFractures/EmbFrac_Compression_CoulombFriction_01                           : 0:00:04 : 0:00:04   : restartcheck
    FAIL CHECK : PoroElastic_Mandel_prism6_smoke_01                          : poroElasticCoupling/PoroElastic_Mandel_prism6_smoke_01                             : 0:00:04 : 0:00:04   : restartcheck
    FAIL CHECK : pknViscosityDominated_poroelastic_01                        : HydrofracturingSolver/pknViscosityDominated_poroelastic_01                         : 0:00:08 : 0:00:08   : restartcheck
    FAIL CHECK : PoroElastic_impermeableFault_smoke_01                       : poroElasticCoupling/PoroElastic_impermeableFault_smoke_01                          : 0:00:04 : 0:00:04   : restartcheck
    FAIL CHECK : PoroElastic_Terzaghi_FIM_02                                 : poroElasticCoupling/PoroElastic_Terzaghi_FIM_02                                    : 0:00:04 : 0:00:08   : restartcheck
    FAIL CHECK : PhaseFieldFracture_VolDevSplit_01                           : phaseFieldFracture/PhaseFieldFracture_VolDevSplit_01                               : 0:00:09 : 0:00:09   : restartcheck
    FAIL CHECK : PoroElastic_staircase_co2_3d_fim_01                         : poroElasticCoupling/PoroElastic_staircase_co2_3d_fim_01                            : 0:00:33 : 0:00:33   : restartcheck
    FAIL CHECK : ContactMechanics_SimpleCubes_01                             : contactMechanics/ContactMechanics_SimpleCubes_01                                   : 0:00:27 : 0:00:27   : restartcheck
    FAIL CHECK : kgdEdgeBased_C3D6_smoke_01                                  : HydrofracturingSolver/kgdEdgeBased_C3D6_smoke_01                                   : 0:00:39 : 0:00:39   : restartcheck
    FAIL CHECK : beamBending_vem_smoke_01                                    : solidMechanicsSSLE/beamBending_vem_smoke_01                                        : 0:00:09 : 0:00:09   : restartcheck
    FAIL CHECK : ThermoPoroElastic_consolidation_fim_02                      : thermoPoromechanics/ThermoPoroElastic_consolidation_fim_02                         : 0:00:06 : 0:00:13   : restartcheck
    FAIL CHECK : PoroElastic_hybridHexPrism_co2_sequential_3d_01             : poroElasticCoupling/PoroElastic_hybridHexPrism_co2_sequential_3d_01                : 0:07:26 : 0:07:26   : restartcheck
    FAIL CHECK : SurfaceGenerator_01                                         : SurfaceGenerator/SurfaceGenerator_01                                               : 0:00:04 : 0:00:04   : restartcheck
    FAIL CHECK : SlipPermeability_pEDFM_smoke_01                             : poromechanicsFractures/SlipPermeability_pEDFM_smoke_01                             : 0:00:06 : 0:00:06   : restartcheck
    FAIL CHECK : PhaseFieldFracture_DamageAndLoad_01                         : phaseFieldFracture/PhaseFieldFracture_DamageAndLoad_01                             : 0:00:25 : 0:00:25   : restartcheck
    FAIL CHECK : kgdToughnessDominated_poroelastic_01                        : HydrofracturingSolver/kgdToughnessDominated_poroelastic_01                         : 0:00:06 : 0:00:06   : restartcheck
    FAIL CHECK : CasedThermoElasticWellbore_ImperfectInterfaces_smoke_01     : wellboreMesh/CasedThermoElasticWellbore_ImperfectInterfaces_smoke_01               : 0:00:06 : 0:00:06   : restartcheck
    FAIL CHECK : kgdValidation_smoke_01                                      : HydrofracturingSolver/kgdValidation_smoke_01                                       : 0:00:10 : 0:00:10   : restartcheck
    FAIL CHECK : singleParticle_01                                           : solidMechanicsMPM/singleParticle_01                                                : 0:00:04 : 0:00:04   : restartcheck
    FAIL CHECK : relaxationTest_02                                           : viscoPlastic/relaxationTest_02                                                     : 0:00:03 : 0:00:06   : restartcheck
    FAIL CHECK : ThermoPoroElastic_conforming_01                             : thermoPoromechanicsFractures/ThermoPoroElastic_conforming_01                       : 0:00:07 : 0:00:07   : restartcheck
    FAIL CHECK : ContactMechanics_SingleFracCompression_01                   : contactMechanics/ContactMechanics_SingleFracCompression_01                         : 0:00:06 : 0:00:06   : restartcheck
    FAIL CHECK : EmbFrac_Compression_Frictionless_01                         : embeddedFractures/EmbFrac_Compression_Frictionless_01                              : 0:00:04 : 0:00:04   : restartcheck
    FAIL CHECK : Sneddon_hydroFrac_smoke_01                                  : HydrofracturingSolver/Sneddon_hydroFrac_smoke_01                                   : 0:00:04 : 0:00:04   : restartcheck
    FAIL CHECK : sedov_01                                                    : sedov/sedov_01                                                                     : 0:00:05 : 0:00:05   : restartcheck
    ---------- : ----------------------------------------------------------- : ---------------------------------------------------------------------------------- : ------- : --------- : ----------
```

**Pull request merged**
