### PR TITLE
refactor: cleanup setMGRStrategy a bit

### PR DESCRIPTION
**Pull request by paveltomin**
this is reopened https://github.com/GEOS-DEV/GEOS/pull/3386
waiting for https://github.com/GEOS-DEV/GEOS/pull/3339 be merged first

### CODE REVIEW

**Comment by paveltomin** [comment]
@victorapm this lost your review because of merging/reopening
could you please have another look?

**Review by victorapm — APPROVED** [review]
Looks good, thanks!

**Comment by paveltomin** [comment]
@CusiniM, @Guotong-Ren, @castelletto1, @frankfeifan, @jhuang2601, @matteofrigo5, @rrsettgast, and/or @ryar9534 need your reviews, Victor already approved

**Comment by paveltomin** [comment]
@CusiniM, @Guotong-Ren, @castelletto1, @frankfeifan, @jhuang2601, @matteofrigo5, @rrsettgast, and/or @ryar9534 please review

**Review by Guotong-Ren — APPROVED** [review]

**Comment by paveltomin** [comment]
@CusiniM, @castelletto1, @frankfeifan, @jhuang2601, @rrsettgast, and/or @ryar9534 please review, it's a simple clean up PR, nothing major

**Review by rrsettgast — APPROVED** [review]

**Review by CusiniM — APPROVED** [review]

**Pull request merged**
