### PR TITLE
Address the issue #2781: add a feature for visualize cells' global index

### LINKED ISSUE #2781: Export Global Cell Index out to VTK output
**What is the requested feature?**
We would like to visualize the Global Cell index used in GEOS by printing these values out as a property on the VTK output.

**Is your request related to a specific problem?**
This is helpful when importing output properties on an input mesh with a different indexing system.

**Describe the solution you'd like**
There is a flag in the XML input file for this feature (`outputGlobalCellsIndex=true` or something equivalent) and the Global Cell index is part of the possible properties to visualize in the VTK output.

### PR DESCRIPTION
**Pull request by sytuannguyen**
This PR addresses the issue #2781 by adding a registerWrapper for cells' global index.

### CODE REVIEW

**Comment by untereiner** [comment]
is the global cell index not stored in `localToGlobalMap` (and `globalToLocalMap` if you want the reverse) ?

**Comment by sytuannguyen** [comment]
> is the global cell index not stored in `localToGlobalMap` (and `globalToLocalMap` if you want the reverse) ?

Indeed, that function will be used to get the global indexes from local ones. Then we add a registerWrapper to output them for visualization as suggested in the issue #2781 by @herve-gross.

**Comment by untereiner** [comment]
ok. but you can already use the `localToGlobalMap` array in a VTKOutput like:
```
    <VTK
      name="vtkOutput"
      fieldNames="{localToGlobalMap}"/>
```

 I am actually using it. What I am saying is that `elementGlobalIndex` will be an array that stores for each element it's global index, exactly what is stored in `localToGlobalMap`.

**Comment by sytuannguyen** [comment]
> ok. but you can already use the `localToGlobalMap` array in a VTKOutput like:
> 
> ```
>     <VTK
>       name="vtkOutput"
>       fieldNames="{localToGlobalMap}"/>
> ```
> 
> I am actually using it. What I am saying is that `elementGlobalIndex` will be an array that stores for each element it's global index, exactly what is stored in `localToGlobalMap`.

I just tried your method, it works perfectly. @untereiner Thank you very much! @herve-gross The issue #2781 is solved then. Do we need a documentation to show this capability?

**Pull request closed without merging**
