### PR TITLE
fix: Fix the sphinx errors present in the readthedocs log

### PR DESCRIPTION
**Pull request by rrsettgast**
There are numerous errors in our readthedocs logs. We need to fix them and add a CI test to make sure errors are not inserted into the docs. Here is the [log](https://github.com/user-attachments/files/16937573/2470101.txt) at the time of this writing.

- [x] Add CI coverage for sphinx errors:
  - test to check readthedocs logs...OR,
  - build sphinx in the CI with the same version of readthedocs...maybe use the [readthedocs docker image](https://hub.docker.com/r/readthedocs/build/tags)
  - Ended up having readthedocs throw the errors...need to see if everyone can view the error log.

Fix Errors/Warnings:
- [x] `/home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/develop/src/docs/sphinx/CompleteXMLSchema.rst:5: ERROR: Document or section may not begin with a transition.`
- [x] `reading sources... [ 86%] docs/sphinx/advancedExamples/validationStudies/carbonStorage/buckleyLeverett/Example
<string>:156: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
<string>:158: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
<string>:160: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.`

- [x] `docs/sphinx/advancedExamples/validationStudies/carbonStorage/isothermalHystInjection/Example
reading sources... [ 86%] docs/sphinx/advancedExamples/validationStudies/carbonStorage/isothermalLeakyWell/Example
<string>:17: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
<string>:19: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
reading sources... [ 87%] docs/sphinx/advancedExamples/validationStudies/carbonStorage/thermalLeakyWell/Example
<string>:18: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
<string>:20: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
<string>:24: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
<string>:26: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.`

- [x] `docs/sphinx/advancedExamples/validationStudies/faultMechanics/intersectFrac/Example
<string>:114: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
<string>:121: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
<string>:127: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.`

- [x] `docs/sphinx/advancedExamples/validationStudies/faultMechanics/singleFracCompression/Example
<string>:106: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
<string>:114: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
<string>:120: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.`

- [x] ` docs/sphinx/advancedExamples/validationStudies/faultMechanics/sneddon/Example
<string>:86: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
<string>:97: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
<string>:108: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.`

- [x] `docs/sphinx/advancedExamples/validationStudies/thermoPoromechanics/thermalConsolidation/Example
<string>:18: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
<string>:20: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
<string>:22: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
<string>:18: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
<string>:20: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
<string>:22: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
<string>:18: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
<string>:20: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
<string>:22: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.`

- [x] `docs/sphinx/advancedExamples/validationStudies/viscoplasticity/RelaxationTest/Example
<string>:215: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
<string>:222: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.`

- [x] `docs/sphinx/advancedExamples/validationStudies/wellboreProblems/casedContactElasticWellbore/Example
<string>:16: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
<string>:17: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.`

- [x] `/home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/coreComponents/physicsSolvers/contact/docs/SolidMechanicsEmbeddedFractures.rst:3: WARNING: Title overline too short.
/home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/coreComponents/physicsSolvers/contact/docs/SolidMechanicsEmbeddedFractures.rst:14: WARNING: Title underline too short.`

- [x] `/home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/coreComponents/physicsSolvers/contact/docs/SolidMechanicsEmbeddedFractures.rst:25: WARNING: start-after pattern not found: <!-- SPHINX_SNEDDON_SOLVER -->`
- [x] coreComponents/schema/docs/CompositionalMultiphaseFVM.rst:34: WARNING: Inline interpreted text or phrase reference start-string without end-string.

- [x] `/home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/coreComponents/physicsSolvers/multiphysics/docs/userTableStressInitialization/Example.rst:94: WARNING: duplicate label probleminitializationpres, other instance in /home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/coreComponents/physicsSolvers/multiphysics/docs/gravityInducedStressInitialization/Example.rst`
- [x] `/home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/coreComponents/physicsSolvers/multiphysics/docs/userTableStressInitialization/Example.rst:102: WARNING: duplicate label probleminitializationszz, other instance in /home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/coreComponents/physicsSolvers/multiphysics/docs/gravityInducedStressInitialization/Example.rst`
- [x] `/home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/coreComponents/schema/docs/CompositionalMultiphaseFVM.rst:34: WARNING: Inline interpreted text or phrase reference start-string without end-string.`
- [x] `/home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/coreComponents/schema/docs/CompositionalMultiphaseHybridFVM.rst:26: WARNING: Inline interpreted text or phrase reference start-string without end-string.`
- [x] `coreComponents/schema/docs/CompositionalMultiphaseFVM.rst:34: WARNING: Inline interpreted text or phrase reference start-string without end-string.`
- [x] `coreComponents/schema/docs/CompositionalMultiphaseHybridFVM.rst:26: WARNING: Inline interpreted text or phrase reference start-string without end-string.`
- [x] `/home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/docs/sphinx/CompleteXMLSchema.rst:5: ERROR: Document or section may not begin with a transition.`
- [x] `/home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/docs/sphinx/advancedExamples/performanceBenchmarks/Index.rst:81: WARNING: Explicit markup ends without a blank line; unexpected unindent.`
- [x] `/home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/docs/sphinx/advancedExamples/validationStudies/poromechanics/Index.rst:5: WARNING: duplicate label validationstudiesfaultmechanics, other instance in /home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/docs/sphinx/advancedExamples/validationStudies/faultMechanics/Index.rst`
- [x] `/home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/docs/sphinx/advancedExamples/validationStudies/poromechanics/mandel/Example.rst:122: WARNING: start-after pattern not found: <!-- SPHINX_MECHANICALSOLVER -->`
- [x] `/home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/docs/sphinx/advancedExamples/validationStudies/poromechanics/mandel/Example.rst:130: WARNING: start-after pattern not found: <!-- SPHINX_SINGLEPHASEFVM -->`
- [x] `/home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/docs/sphinx/advancedExamples/validationStudies/poromechanics/mandel/Example.rst:138: WARNING: start-after pattern not found: <!-- SPHINX_POROMECHANICSSOLVER -->`
- [x] `/home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/docs/sphinx/advancedExamples/validationStudies/thermoPoromechanics/thermalConsolidation/Example.rst:40: WARNING: duplicate label problemsketchfig, other instance in /home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/docs/sphinx/advancedExamples/validationStudies/poromechanics/mandel/Example.rst`
- [x] `/home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/docs/sphinx/advancedExamples/validationStudies/wellboreProblems/casedContactElasticWellbore/Example.rst:4: WARNING: Title overline too short.`

- [x] `/home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/docs/sphinx/advancedExamples/validationStudies/wellboreProblems/casedContactThermoElasticWellbore/Example.rst:114: WARNING: Exception occurred in plotting thermoElastic_casedContactWellbore_temperature
 from /home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/docs/sphinx/advancedExamples/validationStudies/wellboreProblems/casedContactThermoElasticWellbore/thermoElastic_casedContactWellbore_temperature.py:`

- [x] `FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'temperatureHistory_casing.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
/home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/docs/sphinx/advancedExamples/validationStudies/wellboreProblems/casedContactThermoElasticWellbore/Example.rst:126: WARNING: Exception occurred in plotting thermoElastic_casedContactWellbore_displacement
 from /home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/docs/sphinx/advancedExamples/validationStudies/wellboreProblems/casedContactThermoElasticWellbore/thermoElastic_casedContactWellbore_displacement.py:` @sytuannguyen 

- [x] `FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'displacementHistory.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
/home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/docs/sphinx/advancedExamples/validationStudies/wellboreProblems/casedContactThermoElasticWellbore/Example.rst:138: WARNING: Exception occurred in plotting thermoElastic_casedContactWellbore_stress
 from /home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/docs/sphinx/advancedExamples/validationStudies/wellboreProblems/casedContactThermoElasticWellbore/thermoElastic_casedContactWellbore_stress.py:` @sytuannguyen 

- [x] `FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'stressHistory_casing.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
/home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/docs/sphinx/advancedExamples/validationStudies/wellboreProblems/casedThermoElasticWellbore/Example.rst:149: WARNING: end-before pattern not found: 
/home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/docs/sphinx/advancedExamples/validationStudies/wellboreProblems/casedThermoElasticWellbore/Example.rst:215: WARNING: Exception occurred in plotting thermoElastic_casedWellbore_temperature
 from /home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/docs/sphinx/advancedExamples/validationStudies/wellboreProblems/casedThermoElasticWellbore/thermoElastic_casedWellbore_temperature.py:` @sytuannguyen 

- [x] `FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'temperatureHistory_casing.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
/home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/docs/sphinx/advancedExamples/validationStudies/wellboreProblems/casedThermoElasticWellbore/Example.rst:227: WARNING: Exception occurred in plotting thermoElastic_casedWellbore_displacement
 from /home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/docs/sphinx/advancedExamples/validationStudies/wellboreProblems/casedThermoElasticWellbore/thermoElastic_casedWellbore_displacement.py:` @sytuannguyen 

- [x] `FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'displacementHistory.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
/home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/docs/sphinx/advancedExamples/validationStudies/wellboreProblems/casedThermoElasticWellbore/Example.rst:239: WARNING: Exception occurred in plotting thermoElastic_casedWellbore_stress
 from /home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/docs/sphinx/advancedExamples/validationStudies/wellboreProblems/casedThermoElasticWellbore/thermoElastic_casedWellbore_stress.py:` @sytuannguyen 

- [x] `FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'stressHistory_casing.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
/home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/docs/sphinx/advancedExamples/validationStudies/wellboreProblems/dpWellbore/Example.rst:71: WARNING: Exception occurred in plotting dpWellbore_plot
 from /home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/docs/sphinx/advancedExamples/validationStudies/wellboreProblems/dpWellbore/dpWellbore_plot.py:` @sytuannguyen 

- [x] `FileNotFoundError: [Errno 2] No such file or directory: 'DruckerPragerWellbore_benchmark.xml'
/home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/docs/sphinx/advancedExamples/validationStudies/wellboreProblems/edpWellbore/Example.rst:204: WARNING: Exception occurred in plotting edpWellbore_plot
 from /home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/docs/sphinx/advancedExamples/validationStudies/wellboreProblems/edpWellbore/edpWellbore_plot.py:` @sytuannguyen 

- [x] `FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = './stressHistory_rock.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
/home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/docs/sphinx/advancedExamples/validationStudies/wellboreProblems/edpWellbore/Example.rst:212: WARNING: duplicate label edpwellboreverificationfig, other instance in /home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/docs/sphinx/advancedExamples/validationStudies/wellboreProblems/dpWellbore/Example.rst
/home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/docs/sphinx/advancedExamples/validationStudies/wellboreProblems/thermoPoroElasticWellbore/Example.rst:145: WARNING: start-after pattern not found: 
/home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/docs/sphinx/advancedExamples/validationStudies/wellboreProblems/thermoPoroElasticWellbore/Example.rst:211: WARNING: Exception occurred in plotting THM_wellbore_temperature_pressure
 from /home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/docs/sphinx/advancedExamples/validationStudies/wellboreProblems/thermoPoroElasticWellbore/THM_wellbore_temperature_pressure.py:` @sytuannguyen 

- [x] `FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'temperatureHistory_rock.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
/home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/docs/sphinx/advancedExamples/validationStudies/wellboreProblems/thermoPoroElasticWellbore/Example.rst:223: WARNING: Exception occurred in plotting THM_wellbore_displacement
 from /home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/docs/sphinx/advancedExamples/validationStudies/wellboreProblems/thermoPoroElasticWellbore/THM_wellbore_displacement.py:` @sytuannguyen 

- [x] `FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'displacementHistory.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
/home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/docs/sphinx/advancedExamples/validationStudies/wellboreProblems/thermoPoroElasticWellbore/Example.rst:235: WARNING: Exception occurred in plotting THM_wellbore_stress
 from /home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/docs/sphinx/advancedExamples/validationStudies/wellboreProblems/thermoPoroElasticWellbore/THM_wellbore_stress.py:` @sytuannguyen 

- [x] `AttributeError: module 'analyticalResults' has no attribute 'getDataFromXML'`

- [x] `/home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/docs/sphinx/buildGuide/AppleMacOS.rst:4: WARNING: Title underline too short.`
- [x] `/home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/docs/sphinx/buildGuide/AppleMacOS.rst:51: WARNING: Title underline too short.`
- [x] `/home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/docs/sphinx/buildGuide/AppleMacOS.rst:51: WARNING: Title underline too short.`
- [x] `/home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/docs/sphinx/developerGuide/Contributing/index_contributing.rst:2: WARNING: Explicit markup ends without a blank line; unexpected unindent.`
- [x] `/home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/docs/sphinx/developerGuide/Contributing/index_contributing.rst:6: WARNING: toctree contains reference to nonexisting document 'docs/sphinx/developerGuide/Contributing/WorkingInteractivelyOnCI'`
- [x] `/home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/docs/sphinx/tutorials/step02/Tutorial.rst.rst:152: WARNING: line number spec is out of range(1-7): '1-20'`
- [x] `/home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/docs/sphinx/tutorials/step04/Tutorial.rst:85: WARNING: start-after pattern not found: <!-- SPHINX_FEDiscretization -->`
- [x] `/home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/coreComponents/mesh/docs/meshDeveloperGuide.rst:33: WARNING: undefined label: 'meshobjectinstantiationhierarchy'`
- [x] `/home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/docs/sphinx/developerGuide/Contributing/IntegratedTests.rst:533: WARNING: undefined label: 'override test behavior'`
- [x] `/home/docs/checkouts/readthedocs.org/user_builds/geosx-geosx/checkouts/3343/src/pygeosx/pygeosx_documentation.rst:7: WARNING: undefined label: 'pylvarray'`

### CODE REVIEW

**Comment by rrsettgast** [comment]
@sytuannguyen There are errors I assigned to you in the list above. I am going to start enforcing no errors or warnings in sphinx on `develop` asap. These errors must be fixed promptly, or I will need to just comment out the lines, or remove the files. Please fix these errors soon.

**Comment by sytuannguyen** [comment]
> @sytuannguyen There are errors I assigned to you in the list above. I am going to start enforcing no errors or warnings in sphinx on `develop` asap. These errors must be fixed promptly, or I will need to just comment out the lines, or remove the files. Please fix these errors soon.

@rrsettgast These errors are because we have chosen not to add hdf5 files to the repo to reduce its size. Please comment out the lines calling the Python script. We can do this because the PNG figures that are generated by these scripts are already there. However, please do not delete these scripts because they are needed when we want to re-generate those PNG figures.

**Comment by rrsettgast** [comment]
@sytuannguyen 
I asked you to clean up errors that you introduced. It is inappropriate to respond by telling me to fix it for you. This needs to be fixed asap, so I have done it for you. In the future please have some consideration for my time.

**Comment by rrsettgast** [comment]
@cssherman 

Happy! Happy! Joy! Joy! It works!

image

**Review by wrtobin — APPROVED** [review]

**Pull request merged**
