### PR TITLE
Add HYPRE warning

### PR DESCRIPTION
**Pull request by victorapm**
Add warning message to the simulation log for the case when only GEOS is configured with GPU support, but not hypre.

I'm not sure if I put the warning in the right place, so feel free to modify. Thanks!

### CODE REVIEW

**Review by wrtobin — APPROVED** [review]

**Comment by rrsettgast** [comment]
Do we want a warning or error or Compiler time error?

**Comment by sframba** [comment]
> Do we want a warning or error or Compiler time error?

For what it's worth, compiling with cuda support for GEOS but without cuda for hypre is definitely possible and everything seems to work well. We have been doing it for a while to avoid issues with some missing hypre features on cuda (although I deduce from this PR that everything is fine now?)

**Comment by wrtobin** [comment]
Allowing the GEOS+GPU - HYPRE+CPU build combo is very useful in debugging failures on new platforms, I definitely don't want to drop support for it.

**Review by jhuang2601 — APPROVED** [review]

**Comment by paveltomin** [comment]
move to merge queue?

**Pull request merged**
