### PR TITLE
fix: make new gravity treatment from #3337 an option

### PR DESCRIPTION
**Pull request by paveltomin**
disabled by default since SPE11 case degradations were observed

### CODE REVIEW

**Review by victorapm — APPROVED** [review]
This PR matches with the reference results for spe11b. Thanks!

spe11b-times

**Comment by paveltomin** [comment]
@CusiniM and @ryar9534 let's please move this fix quickly into develop, critical for spe11

**Review by CusiniM — APPROVED** [review]

**Comment by CusiniM** [comment]
I don' t know that we really need 2 options for the treatment of gravity. In general, I think that what @paveltomin had introduced made more sense... I am not too sure why it would have such a large impact on convergence.

**Comment by rrsettgast** [comment]
@paveltomin The term `newGravity` is quite uninformative. Can you create descriptive options for the "gravity treatment" so that developers/users know what the treatments are?

**Comment by paveltomin** [comment]
> @paveltomin The term `newGravity` is quite uninformative. Can you create descriptive options for the "gravity treatment" so that developers/users know what the treatments are?

Ok will do

**Comment by paveltomin** [comment]
> @paveltomin The term `newGravity` is quite uninformative. Can you create descriptive options for the "gravity treatment" so that developers/users know what the treatments are?

is this https://github.com/GEOS-DEV/GEOS/pull/3486 better?

**Pull request merged**
