### PR TITLE
fix: testLifoStorage CI failures

### PR DESCRIPTION
**Pull request by sframba**
The `testLifoStorage` unit tests still occasionally fail (issue #3355).
After #3362, fails seem to only happen in the `LifoStorageBufferOnCUDANoDeviceBuffer` test. This is a corner case as it uses a zero-size device buffer which might be buggy. 
To help smooth the CI process, I propose disabling this specific test for now, pending further review.

### CODE REVIEW

**Review by jiemeng-total — APPROVED** [review]

**Review by rrsettgast — APPROVED** [review]
I suggest just commenting out the test, including a comment indicating the problem, and the situations that this tests is providing coverage for.

**Comment by rrsettgast** [comment]
@wrtobin Do you have any comment on this? I think it still needs to be fixed, but this functionality is for the Makutu team, so it won't affect the rest of the code.

**Comment by wrtobin** [comment]
I agree that commenting out and documenting the test (with a link back to this MR or an open issue) would be fine here. 

We still want it to be fixed of course, but since the FIFO storage stuff is only used for the Makutu team it should be fine. One would hope that in use the FIFO storage wouldn't use size-0 buffers on device (since that seems counter to the intent of the container), though having that case not be catastrophic would certainly be preferable. Further, if the intent in practical use is actually never to have a size 0 buffer on device with the LIFO container, we could add a runtime check and error out if it actually happens.

**Comment by sframba** [comment]
I'm going to merge this since it will help gain some time in handling the merge queue (it will avoid some CI re-runs, hopefully)

**Pull request merged**
