### PR TITLE
Fix function interface for poroVisoPlastic models

### PR DESCRIPTION
**Pull request by jhuang2601**
This PR 
- [x] fix function interface to enable `PorousViscoDruckerPrager` and `PorousViscoExtendedDruckerPrager` and `PorousViscoModifiedCamClay`
- [x] add smoke tests for these poroviscoplastic models to the integratedTests 
       https://github.com/GEOS-DEV/integratedTests/pull/80

### CODE REVIEW

**Review by CusiniM — COMMENTED** [review]
You need to add them here too https://github.com/GEOS-DEV/GEOS/blob/39e75de52fbb5b36d862ddb7adc95c16250771e1/src/coreComponents/physicsSolvers/multiphysics/poromechanicsKernels/PoromechanicsKernels.cmake#L16

**Comment by jhuang2601** [comment]
> You need to add them here too
> 
> https://github.com/GEOS-DEV/GEOS/blob/39e75de52fbb5b36d862ddb7adc95c16250771e1/src/coreComponents/physicsSolvers/multiphysics/poromechanicsKernels/PoromechanicsKernels.cmake#L16

I've already added them there.

**Comment by CusiniM** [comment]
> > You need to add them here too
> > https://github.com/GEOS-DEV/GEOS/blob/39e75de52fbb5b36d862ddb7adc95c16250771e1/src/coreComponents/physicsSolvers/multiphysics/poromechanicsKernels/PoromechanicsKernels.cmake#L16
> 
> I've already added them there.

then it should work. Do you get an error?

**Comment by jhuang2601** [comment]
> > > You need to add them here too
> > > https://github.com/GEOS-DEV/GEOS/blob/39e75de52fbb5b36d862ddb7adc95c16250771e1/src/coreComponents/physicsSolvers/multiphysics/poromechanicsKernels/PoromechanicsKernels.cmake#L16
> > 
> > 
> > I've already added them there.
> 
> then it should work. Do you get an error?

Unfortunately, following error was received:
```
***** ERROR
***** LOCATION: /shared/data1/Users/j0551570/Compilation/Develop_120523/GEOS/src/coreComponents/dataRepository/ObjectCatalog.hpp:190
***** Controlling expression (should be false): true
***** Rank 1: Could not find keyword "PorousViscoExtendedDruckerPrager" in this context. Please be sure that all your keywords are properly spelled or that input file parameters have not changed.
All available keys are: [
BiotPorosity,
BlackOilFluid,
BrooksCoreyBakerRelativePermeability,
BrooksCoreyCapillaryPressure,
BrooksCoreyRelativePermeability,
CarmanKozenyPermeability,
CeramicDamage,
CO2BrineEzrokhiFluid,
CO2BrineEzrokhiThermalFluid,
CO2BrinePhillipsFluid,
CO2BrinePhillipsThermalFluid,
CompositionalMultiphaseFluid,
CompositonalTwoPhaseFluidPengRobinson,
CompositonalTwoPhaseFluidSoaveRedlichKwong,
CompressibleSinglePhaseFluid,
CompressibleSolidCarmanKozenyPermeability,
CompressibleSolidConstantPermeability,
CompressibleSolidExponentialDecayPermeability,
CompressibleSolidParallelPlatesPermeability,
CompressibleSolidSlipDependentPermeability,
CompressibleSolidWillisRichardsPermeability,
ConstantDiffusion,
ConstantPermeability,
Coulomb,
DamageElasticIsotropic,
DamageSpectralElasticIsotropic,
DamageVolDevElasticIsotropic,
DeadOilFluid,
DelftEgg,
DruckerPrager,
ElasticIsotropic,
ElasticIsotropicPressureDependent,
ElasticOrthotropic,
ElasticTransverseIsotropic,
ExponentialDecayPermeability,
ExtendedDruckerPrager,
FrictionlessContact,
JFunctionCapillaryPressure,
LinearIsotropicDispersion,
ModifiedCamClay,
MultiPhaseConstantThermalConductivity,
MultiPhaseVolumeWeightedThermalConductivity,
NullModel,
ParallelPlatesPermeability,
ParticleFluid,
PerfectlyPlastic,
PermeabilityBase,
PorousDelftEgg,
PorousDruckerPrager,
PorousElasticIsotropic,
PorousElasticOrthotropic,
PorousElasticTransverseIsotropic,
PorousExtendedDruckerPrager,
PorousModifiedCamClay,
PressurePorosity,
ProppantPermeability,
ProppantPorosity,
ProppantSlurryFluid,
ProppantSolidProppantPermeability,
ReactiveBrine,
ReactiveBrineThermal,
SinglePhaseConstantThermalConductivity,
SlipDependentPermeability,
SolidInternalEnergy,
TableCapillaryPressure,
TableRelativePermeability,
TableRelativePermeabilityHysteresis,
ThermalCompressibleSinglePhaseFluid,
VanGenuchtenBakerRelativePermeability,
VanGenuchtenCapillaryPressure,
ViscoDruckerPrager,
ViscoExtendedDruckerPrager,
ViscoModifiedCamClay,
WillisRichardsPermeability
]

```

**Comment by CusiniM** [comment]
okay, I have fixed it. There was a bug in `catalogName()` for `PorousSolid`. It seems to work now.

**Review by CusiniM — APPROVED** [review]

**Comment by jhuang2601** [comment]
> okay, I have fixed it. There was a bug in `catalogName()` for `PorousSolid`. It seems to work now.

Great, it works now.

**Review by paveltomin — APPROVED** [review]

**Comment by CusiniM** [comment]
anyone can merge this as soon as CI is done. IntegratedTests already merged.

**Pull request merged**
