### PR TITLE
Add RESQML input

### PR DESCRIPTION
**Pull request by untereiner**
created branch for adding RESQML input via [fesapi](https://github.com/F2I-Consulting/fesapi/).

### CODE REVIEW

**Comment by untereiner** [comment]
Hi! 
To avoid too many conflicts until this draft will be ready, I suggest to turn this pull request into three ones:
- 1st one: extract vtk logic into new files
- 2nd one: correspond to his sister one in the third parties just to add fesapi in the config files
- 3rd one: the draft where I work on the RESQML input/output files 

What do you think ?

**Comment by klevzoff** [comment]
> To avoid too many conflicts until this draft will be ready, I suggest to turn this pull request into three ones:
> 
> * 1st one: extract vtk logic into new files, mergeable quickly
> * 2nd one: correspond to his sister one in the third parties just to add fesapi in the config files, mergeable quickly
> * 3rd one: the draft where I work on the RESQML input/output files
> 
> What do you think ?

Sounds like a good plan :+1:

**Comment by TotoGaz** [comment]
> Hi! To avoid too many conflicts until this draft will be ready, I suggest to turn this pull request into three ones:
> 
> * 1st one: extract vtk logic into new files, mergeable quickly
> * 2nd one: correspond to his sister one in the third parties just to add fesapi in the config files, mergeable quickly
> * 3rd one: the draft where I work on the RESQML input/output files
> 
> What do you think ?

We can start like this.
It would be interested to get a more precise of what you want to implement first.

Is Gaetan B. going to run a first CR?

**Comment by untereiner** [comment]
I am going to implement the load of:
- unstructured grids 
- regions from RESQML subrepresentations
- cell attributes from RESQML properties

What I do not know yet is how are handled the units of measure and if it exists a field kind catalog in GEOSX.

**Comment by untereiner** [comment]
Hi @TotoGaz, @klevzoff, @francoishamon. 
If you have time could you start looking at this PR ? There are two builds failing because they run out of time. I don't know what I can unplug to be 
It's a big piece, it will probably take time to be reviewed.

**Comment by untereiner** [comment]
@TotoGaz I reworked to contribution to simplify it. Would it be possible for you to review it ?

**Comment by herve-gross** [comment]
@francoishamon @TotoGaz or @klevzoff can you start reviewing this PR? If not, please indicate who else should review it. Thanks!

**Comment by TotoGaz** [comment]
> @francoishamon @TotoGaz or @klevzoff can you start reviewing this PR? If not, please indicate who else should review it. Thanks!

Hello, as I previously discussed, we'd like this PR to be first reviewed by the original project manager.
Our bandwidth is really limited.

**Pull request closed without merging**
