### PR TITLE
Full sync for nonlinear solver params in CoupledSolver (used for fully coupled mode)

### PR DESCRIPTION
**Pull request by paveltomin**

### CODE REVIEW

**Comment by paveltomin** [comment]
review anyone please?

**Review by castelletto1 — APPROVED** [review]
Looks good to me, thank you. Do we need new baselines?

**Comment by paveltomin** [comment]
> Looks good to me, thank you. Do we need new baselines?

thanks, @castelletto1, let me double check that

**Review by sohailwaziri — APPROVED** [review]

**Comment by paveltomin** [comment]
> > Looks good to me, thank you. Do we need new baselines?
> 
> thanks, @castelletto1, let me double check that

@castelletto1 you were right, it does need new baselines

**Pull request closed without merging**
