### PR TITLE
injection example fix

### PR DESCRIPTION
**Pull request by arng40**
Correction of SimpleCO2InjTutorial_smoke example due to incorrect values on :
- pvtgas.txt,
- pvtliquid.txt,
- co2flash.txt.

https://github.com/GEOS-DEV/integratedTests/pull/102

### CODE REVIEW

**Review by MelReyCG — APPROVED** [review]
Seems OK to me.

**Comment by paveltomin** [comment]
you may need to also modify https://geosx-geosx.readthedocs-hosted.com/en/latest/docs/sphinx/basicExamples/co2Injection/Example.html

**Comment by arng40** [comment]
Is this log ok ?
```
ATS END OF RUN STARTED January 12, 2024 16:01:06
    Status     : TestCase                              : Directory                                                    : Elapsed : Resources : TestStep  
    ---------- : ------------------------------------- : ------------------------------------------------------------ : ------- : --------- : ----------
    FAIL CHECK : PoroElastic_impermeableFault_smoke_01 : poroElasticCoupling/PoroElastic_impermeableFault_smoke_01    : 0:00:05 : 0:00:05   : restartcheck
    FAIL CHECK : PoroElastic_permeableFault_smoke_01   : poroElasticCoupling/PoroElastic_permeableFault_smoke_01      : 0:00:05 : 0:00:05   : restartcheck
    FAIL CHECK : staircase_co2_wells_hybrid_3d_01      : compositionalMultiphaseWell/staircase_co2_wells_hybrid_3d_01 : 0:00:43 : 0:00:43   : restartcheck
    FAIL CHECK : staircase_co2_wells_3d_01             : compositionalMultiphaseWell/staircase_co2_wells_3d_01        : 0:00:34 : 0:00:34   : restartcheck
    ---------- : ------------------------------------- : ------------------------------------------------------------ : ------- : --------- : ----------
```

**Comment by paveltomin** [comment]
> Is this log ok ?
> 
> ```
> ATS END OF RUN STARTED January 12, 2024 16:01:06
>     Status     : TestCase                              : Directory                                                    : Elapsed : Resources : TestStep  
>     ---------- : ------------------------------------- : ------------------------------------------------------------ : ------- : --------- : ----------
>     FAIL CHECK : PoroElastic_impermeableFault_smoke_01 : poroElasticCoupling/PoroElastic_impermeableFault_smoke_01    : 0:00:05 : 0:00:05   : restartcheck
>     FAIL CHECK : PoroElastic_permeableFault_smoke_01   : poroElasticCoupling/PoroElastic_permeableFault_smoke_01      : 0:00:05 : 0:00:05   : restartcheck
>     FAIL CHECK : staircase_co2_wells_hybrid_3d_01      : compositionalMultiphaseWell/staircase_co2_wells_hybrid_3d_01 : 0:00:43 : 0:00:43   : restartcheck
>     FAIL CHECK : staircase_co2_wells_3d_01             : compositionalMultiphaseWell/staircase_co2_wells_3d_01        : 0:00:34 : 0:00:34   : restartcheck
>     ---------- : ------------------------------------- : ------------------------------------------------------------ : ------- : --------- : ----------
> ```

staircase_co2_wells_hybrid_3d_01      and staircase_co2_wells_3d_01             should work
i guess they are using same input files as you changed, that's why there are some diffs
please double check, the baselines may need to be updated

by the way, should we include injection example also in integrated tests?

**Review by MelReyCG — APPROVED** [review]

**Comment by arng40** [comment]
I have a few questions @paveltomin 
- The staircase examples are based on the same PVT tables. 
- These examples work well, but we will have to rebaseline.
- However, it seems that the components of "simpleCo2InjTutorial" are already tested elsewhere, thus is it necessary to add it to the built-in tests?

**Comment by paveltomin** [comment]
> * However, it seems that the components of "simpleCo2InjTutorial" are already tested elsewhere, thus is it necessary to add it to the built-in tests?

even if components are tested, i don't think the whole case is tested anywhere, that's why it would make sense to include it into integratedTests, since it's in the documentation and we need to make sure it always works

**Comment by CusiniM** [comment]
> > * However, it seems that the components of "simpleCo2InjTutorial" are already tested elsewhere, thus is it necessary to add it to the built-in tests?
> 
> even if components are tested, i don't think the whole case is tested anywhere, that's why it would make sense to include it into integratedTests, since it's in the documentation and we need to make sure it always works

as long as it is not too large. We really need to start forcing all smoke tests to run in less than 1 minute.

**Comment by paveltomin** [comment]
The supposedly fixed case still can not finish - the time step being chop many time and then simulation stops.
Could you please check on you side if it can run to the end?

**Comment by MelReyCG** [comment]
Hi there. I tested this case on Pangea 2 and did not encountered this issue @paveltomin
Here is the log I got :   
[output.txt](https://github.com/GEOS-DEV/GEOS/files/14283582/output.txt)

**Comment by paveltomin** [comment]
> Hi there. I tested this case on Pangea 2 and did not encountered this issue @paveltomin Here is the log I got : [output.txt](https://github.com/GEOS-DEV/GEOS/files/14283582/output.txt)

Yes, you are right, it runs just fine
Sorry for my mistake

**Pull request merged**
