### PR TITLE
Correct namespaces which were not respecting camelCase convention

### PR DESCRIPTION
**Pull request by TotoGaz**
Kept some `PVT`,`LAI` prefixes nevertheless.

See https://geosx-geosx.readthedocs-hosted.com/en/latest/docs/sphinx/developerGuide/Contributing/CodeStyle.html?highlight=naming%20conventions#namespace-names

### CODE REVIEW

**Review by joshua-white — APPROVED** [review]
Looks great to me.  Thanks for cleaning this up.

**Review by rrsettgast — APPROVED** [review]
Awesome. Thanks for doing this.

**Review by francoishamon — APPROVED** [review]
Thanks @TotoGaz

**Comment by TotoGaz** [comment]
Next action is to activate https://www.sonarqube.org/ 😉 
I thought there was something free for open-source projects, but I'm not sure anymore.

**Pull request merged**
