### PR TITLE
Remove travis

### PR DESCRIPTION
**Pull request by TotoGaz**
- Removes travis.
- Removes the epic GHA.
- Fix the `geos` installation folder so it uses the hash.

### CODE REVIEW

**Review by bmhan12 — APPROVED** [review]
Should also rename the `travis_build_and_test.sh` script, or maybe combine it with the `ci_build_and_test.sh` script?

The scripts:
https://github.com/GEOS-DEV/GEOS/blob/991327d913654ce589c80b17c58ea6d8146cc7b6/scripts/ci_build_and_test.sh#L35

https://github.com/GEOS-DEV/GEOS/blob/develop/scripts/travis_build_and_test.sh

**Comment by TotoGaz** [comment]
> Should also rename the `travis_build_and_test.sh` script, or maybe combine it with the `ci_build_and_test.sh` script?

I've quickly looked at it. I should definitely rename it, but I'm not sure the two scripts can be merged.

**Comment by bmhan12** [comment]
> I've quickly looked at it. I should definitely rename it, but I'm not sure the two scripts can be merged.
Renaming works for me.

**Review by bmhan12 — APPROVED** [review]

**Comment by TotoGaz** [comment]
@jhuang2601 was able to validate that we the auto deployments are working.
@rrsettgast I think we can have this PR merged: we're running travis no more. Are you OK?

**Review by jhuang2601 — APPROVED** [review]
Great job!

**Pull request merged**
