### PR TITLE
Adding viscoplasticity 

### PR DESCRIPTION
**Pull request by shabnamjs**
created branch for adding viscoplasticity (Duvaut-Lions model)

### CODE REVIEW

**Comment by jhuang2601** [comment]
@sytuannguyen @herve-gross 
How is the progress of the PR? If viscoDelftEgg model has been added? Besides using triaxialDriver, can we run full geometric problems (with mesh and BCs) for both viscoplastic and poro-viscoplastic deformation? How about to prepare some smoke examples and add them to the integratedTests to conclude the development of this branch?

**Comment by sytuannguyen** [comment]
@joshua-white @shabnamjs Hi Josh, Shabnam, do you want to merge this PR at this state as all the implemented models were validated, using Triaxial Driver, against reference results or you want to add also the model visco DelftEgg?

**Comment by sytuannguyen** [comment]
> 

I suggest to add validation examples and integrated tests with complex Geometry and BCs in separate PR after this PR is merged. @joshua-white how do you think?

**Comment by joshua-white** [comment]
Hey @jhuang2601 and @sytuannguyen.  To run BVP we will need another PR to go in first, to slightly restructure the constitutive hierarchy.  If we are happy with the current capabilities on this branch, I propose @shabnamjs catches it up to develop and merges it.  We can then add the BVP support in a later PR.

Regarding DelftEgg, @shabnamjs will have to weigh in on that one.  @shabnamjs I think we can use the identical approach as we did for MCC, right?

**Comment by sytuannguyen** [comment]
> Hey @jhuang2601 and @sytuannguyen. To run BVP we will need another PR to go in first, to slightly restructure the constitutive hierarchy. If we are happy with the current capabilities on this branch, I propose @shabnamjs catches it up to develop and merges it. We can then add the BVP support in a later PR.
> 
> Regarding DelftEgg, @shabnamjs will have to weigh in on that one. @shabnamjs I think we can use the identical approach as we did for MCC, right?

I would propose to merge this branch at the present state after passing all the travis/docs builds and integratedTests as it is quite old already and all the implemented models were propertly validated. After merging this PR, @jhuang2601 and I will add some more sophisticated validation examples. Visco DelftEgg would be added after in a separete PR after restructure of the constitutive hierarchy as you mentioned. @joshua-white @herve-gross how do you think?

**Comment by jhuang2601** [comment]
> > Hey @jhuang2601 and @sytuannguyen. To run BVP we will need another PR to go in first, to slightly restructure the constitutive hierarchy. If we are happy with the current capabilities on this branch, I propose @shabnamjs catches it up to develop and merges it. We can then add the BVP support in a later PR.
> > Regarding DelftEgg, @shabnamjs will have to weigh in on that one. @shabnamjs I think we can use the identical approach as we did for MCC, right?
> 
> I would propose to merge this branch at the present state after passing all the travis/docs builds and integratedTests as it is quite old already and all the implemented models were propertly validated. After merging this PR, @jhuang2601 and I will add some more sophisticated validation examples. Visco DelftEgg would be added after in a separete PR after restructure of the constitutive hierarchy as you mentioned. @joshua-white @herve-gross how do you think?

@shabnamjs @sytuannguyen Instead of drifting away and getting stuck, I would suggest to merge this branch and then plan next step development for this topic.

**Comment by francoishamon** [comment]
I am closing this PR in favor of https://github.com/GEOS-DEV/GEOS/pull/2377
All the content of this PR has been updated and merged into `develop` with minor modifications to pass the CI tests

**Pull request closed without merging**
