### PR TITLE
MGR recipe for thermal multiphase coupled flow-wellbore

### PR DESCRIPTION
**Pull request by jafranc**
This PR is creating a new MGR decomposition recipe adding thermal treatment in Multiphase flow in reservoir-wellbore coupled solver. It follows CPTR (#1836) strategy adding isolation of wellbore in their own block.

It will be used in SPE11-csp case B.

### CODE REVIEW

**Comment by paveltomin** [comment]
can someone describe in math equations what this means:
```
                    m_levelFRelaxMethod[0] = MGRFRelaxationMethod::singleLevel; //default, i.e. Jacobi
                    m_levelFRelaxType[0] = MGRFRelaxationType::gsElimWInverse; // gaussian elimination for the well block
                    m_levelInterpType[0] = MGRInterpolationType::blockJacobi;
                    m_levelRestrictType[0] = MGRRestrictionType::injection;
                    m_levelCoarseGridMethod[0] = MGRCoarseGridMethod::galerkin;

                    m_levelFRelaxMethod[1] = MGRFRelaxationMethod::singleLevel; //default, i.e. Jacobi
                    m_levelInterpType[1] = MGRInterpolationType::jacobi; // Diagonal scaling (Jacobi)
                    m_levelRestrictType[1] = MGRRestrictionType::injection;
                    m_levelCoarseGridMethod[1] = MGRCoarseGridMethod::galerkin; // Standard Galerkin

                    m_levelFRelaxMethod[2] = MGRFRelaxationMethod::singleLevel; //default, i.e. Jacobi
                    m_levelInterpType[2] = MGRInterpolationType::injection; // Injection
                    m_levelRestrictType[2] = MGRRestrictionType::injection;
                    m_levelCoarseGridMethod[2] = MGRCoarseGridMethod::cprLikeBlockDiag; // Non-Galerkin Quasi-IMPES CPR

                    // Block Jacobi for the system made of pressure, temperature, and densities
                    m_levelSmoothType[1] = 0;
                    m_levelSmoothIters[1] = 1;
#if GEOS_USE_HYPRE_DEVICE != GEOS_USE_HYPRE_HIP
                    // ILU smoothing for the system made of pressure, temperature, and densities (except the last one)
                    m_levelSmoothType[2] = 16;
                    m_levelSmoothIters[2] = 1;
#endif
```
i keep having hard time to translate, sorry

**Comment by jhuang2601** [comment]
@jafranc What is the status of this PR?

**Comment by jafranc** [comment]
> @jafranc What is the status of this PR?

It is outdated for sure and on a back burner as we must resolve any possible issue with AMG and IMPES reduction first, making sure to have consistent story here.

**Comment by rrsettgast** [comment]
@castelletto1 @victorapm can you take a look at this and determine if it should be closed or merged into develop?

**Comment by victorapm** [comment]
It seems @tjb-ltk has already added this in his PR #3156 

https://github.com/GEOS-DEV/GEOS/blob/develop/src/coreComponents/linearAlgebra/interfaces/hypre/mgrStrategies/ThermalCompositionalMultiphaseReservoirFVM.hpp

**Comment by jafranc** [comment]
Already tackled by #3156

**Pull request closed without merging**
