### PR TITLE
Linking gRPC to GEOS

### PR DESCRIPTION
**Pull request by MichaelSekachev**

### CODE REVIEW

**Comment by rrsettgast** [comment]
@MichaelSekachev Can you post your link command and the subsequent error on this PR?

**Comment by MichaelSekachev** [comment]
> @MichaelSekachev Can you post your link command and the subsequent error on this PR?

@rrsettgast. Indeed, if I saw the command I might have spotted the issue. So how do I do that? Please find attached the full log of the make command...
`make -j 16 2>&1 | tee -a output-geos-make-rdhpc8-debug.txt`
[output-geos-make-rdhpc8-debug.txt](https://github.com/user-attachments/files/16025362/output-geos-make-rdhpc8-debug.txt)

**Comment by rrsettgast** [comment]
@MichaelSekachev 
```
make VERBOSE=1
```

**Comment by MichaelSekachev** [comment]
> @MichaelSekachev
> 
> ```
> make VERBOSE=1
> ```

Thanks. Indeed, it looks like the libraries are not linked against. No `-lgrpc++` or anything else. Please see the attached log:
[output-geos-make-rdhpc8-debug-verbose.txt](https://github.com/user-attachments/files/16025493/output-geos-make-rdhpc8-debug-verbose.txt)

**Comment by rrsettgast** [comment]
Do you know if cmake was used to build grpc?

**Comment by MichaelSekachev** [comment]
> Do you know if cmake was used to build grpc?

I would say, yes. I

**Comment by rrsettgast** [comment]
there should be a way to include the library using the cmake files generated by the build of gfrc. Are there some cmake files in the lib directory of the gfrc install?

**Comment by MichaelSekachev** [comment]
> there should be a way to include the library using the cmake files generated by the build of gfrc. Are there some cmake files in the lib directory of the gfrc install?

I don't really know how CMake works. Whe grpc finishes installing it creates two folders `lib` and lib64` with the following contents:
Screenshot 2024-06-28 221355

image

**Comment by rrsettgast** [comment]
hello @MichaelSekachev I added a commit as an example to import packages. I don't really recall the details of importing cmake targets. @wrtobin Do you recall the proper way to import cmake targets from the information shown above?

**Comment by MichaelSekachev** [comment]
> hello @MichaelSekachev I added a commit as an example to import packages. I don't really recall the details of importing cmake targets. @wrtobin Do you recall the proper way to import cmake targets from the information shown above?

HI @rrsettgast . Thank you. So, the idea is to try to use `find_package` instead of `find_and_register`. Your commit seem to have a lot of unrelated changes. This is perhaps because my branch is based on a one year old version of the code. So, I need to create a `FindGrpc.cmake` file, right? Byt the way, I am currently on vacation and will be out of town for one week starting tomorrow. I will do things as I am able to. Thank you for all of your help.

**Comment by rrsettgast** [comment]
> > hello @MichaelSekachev I added a commit as an example to import packages. I don't really recall the details of importing cmake targets. @wrtobin Do you recall the proper way to import cmake targets from the information shown above?
> 
> HI @rrsettgast . Thank you. So, the idea is to try to use `find_package` instead of `find_and_register`. Your commit seem to have a lot of unrelated changes. This is perhaps because my branch is based on a one year old version of the code. So, I need to create a `FindGrpc.cmake` file, right? Byt the way, I am currently on vacation and will be out of town for one week starting tomorrow. I will do things as I am able to. Thank you for all of your help.

I see a bunch of `*.cmake` files in your tree. Those are the ones you want. So you are good. Can you put up a tarball with your `*.cmake` files?

**Comment by untereiner** [comment]
Hello @MichaelSekachev [Here](https://github.com/googleapis/google-cloud-cpp/blob/main/cmake/FindgRPC.cmake) is one or just use `find_package(gRPC CONFIG REQUIRED)` as shown [here](https://cmake.org/cmake/help/latest/module/FindProtobuf.html)

**Comment by MichaelSekachev** [comment]
@untereiner @rrsettgast 

Hi guys. Thank you for the tips you provided while I was on vacation. I am back and I tried what you suggested in the commit I just pushed (https://github.com/GEOS-DEV/GEOS/pull/3192/commits/da2108ce9b802f6ab9354b4b0f3856bdeb862ac5). Unfortunately, I still have the same linking issue as before. 
In the commit above, please note that I had to use find_package() for several other packages before the final find_package(gRPC) would execute correctly. I also used the following parameters in set_property() call:
```
    set_property(TARGET gRPC::grpc
                 APPEND PROPERTY INTERFACE_SYSTEM_INCLUDE_DIRECTORIES
                 grpc_INCLUDE_DIR)
```
instead of what was suggested by Randy (used `gRPC:grpc` instead of `grpc` and `grpc_INCLUDE_DIR` instead of `grpc_INCLUDE_PATH`)
```
    set_property( TARGET grpc
                  APPEND PROPERTY INTERFACE_SYSTEM_INCLUDE_DIRECTORIES
                  ${grpc_INCLUDE_PATH} )
```

This linking command is still:
```
/usr/bin/g++  -Wall -Wextra       -Werror  -fopenmp  -Wall -Wextra -Wpedantic -pedantic-errors -Wshadow -Wfloat-equal -Wcast-align -Wcast-qual  -g -Wno-unused-parameter -Wno-unused-variable  -Wl,--export-dynamic -rdynamic -fopenmp -Wl,-rpath -Wl,/hrtc/apps/mpi/openmpi/x86_64/centos8/4.1.4/gcc/8.5.0/lib -Wl,-rpath -Wl,/hrtc/apps/devtools/ucx/x86_64/centos8/1.10.0/gcc/8.5.0/cuda.11.5/lib -Wl,--enable-new-dtags -L/hrtc/apps/devtools/ucx/x86_64/centos8/1.10.0/gcc/8.5.0/cuda.11.5/lib -pthread CMakeFiles/geosx.dir/main/main.cpp.o -o bin/geosx  -Wl,-rpath,/shared/data1/Projects/ixdev/msekachev/geos/GEOS/build-rdhpc8-CPU-debug/lib:/shared/data1/Projects/ixdev/msekachev/geos/thirdPartyLibs/install-rdhpc8-CPU-debug/caliper/lib64:/shared/data1/Projects/ixdev/msekachev/geos/thirdPartyLibs/install-rdhpc8-CPU-debug/vtk/lib:/shared/data1/Projects/ixdev/msekachev/geos/thirdPartyLibs/install-rdhpc8-CPU-debug/suitesparse/lib:/shared/data1/Projects/ixdev/msekachev/geos/thirdPartyLibs/install-rdhpc8-CPU-debug/superlu_dist/lib64:: lib/libgeosx_core.so /shared/data1/Projects/ixdev/msekachev/geos/thirdPartyLibs/install-rdhpc8-CPU-debug/caliper/lib64/libcaliper.so.2.8.0 /shared/data1/Projects/ixdev/msekachev/geos/thirdPartyLibs/install-rdhpc8-CPU-debug/mathpresso/lib/libmathpresso.a /shared/data1/Projects/ixdev/msekachev/geos/thirdPartyLibs/install-rdhpc8-CPU-debug/vtk/lib/libvtkFiltersParallelDIY2-9.1.so.9.1.0 /shared/data1/Projects/ixdev/msekachev/geos/thirdPartyLibs/install-rdhpc8-CPU-debug/vtk/lib/libvtkFiltersParallel-9.1.so.9.1.0 /shared/data1/Projects/ixdev/msekachev/geos/thirdPartyLibs/install-rdhpc8-CPU-debug/vtk/lib/libvtkFiltersExtraction-9.1.so.9.1.0 /shared/data1/Projects/ixdev/msekachev/geos/thirdPartyLibs/install-rdhpc8-CPU-debug/vtk/lib/libvtkFiltersHybrid-9.1.so.9.1.0 /shared/data1/Projects/ixdev/msekachev/geos/thirdPartyLibs/install-rdhpc8-CPU-debug/vtk/lib/libvtkFiltersModeling-9.1.so.9.1.0 /shared/data1/Projects/ixdev/msekachev/geos/thirdPartyLibs/install-rdhpc8-CPU-debug/vtk/lib/libvtkFiltersSources-9.1.so.9.1.0 /shared/data1/Projects/ixdev/msekachev/geos/thirdPartyLibs/install-rdhpc8-CPU-debug/vtk/lib/libvtkFiltersTexture-9.1.so.9.1.0 /shared/data1/Projects/ixdev/msekachev/geos/thirdPartyLibs/install-rdhpc8-CPU-debug/vtk/lib/libvtkParallelDIY-9.1.so.9.1.0 /shared/data1/Projects/ixdev/msekachev/geos/thirdPartyLibs/install-rdhpc8-CPU-debug/vtk/lib/libvtkFiltersGeneral-9.1.so.9.1.0 /shared/data1/Projects/ixdev/msekachev/geos/thirdPartyLibs/install-rdhpc8-CPU-debug/vtk/lib/libvtkFiltersGeometry-9.1.so.9.1.0 /shared/data1/Projects/ixdev/msekachev/geos/thirdPartyLibs/install-rdhpc8-CPU-debug/vtk/lib/libvtkFiltersCore-9.1.so.9.1.0 /shared/data1/Projects/ixdev/msekachev/geos/thirdPartyLibs/install-rdhpc8-CPU-debug/vtk/lib/libvtkIOParallelXML-9.1.so.9.1.0 /shared/data1/Projects/ixdev/msekachev/geos/thirdPartyLibs/install-rdhpc8-CPU-debug/vtk/lib/libvtkParallelMPI-9.1.so.9.1.0 /shared/data1/Projects/ixdev/msekachev/geos/thirdPartyLibs/install-rdhpc8-CPU-debug/vtk/lib/libvtkParallelCore-9.1.so.9.1.0 /shared/data1/Projects/ixdev/msekachev/geos/thirdPartyLibs/install-rdhpc8-CPU-debug/vtk/lib/libvtkIOLegacy-9.1.so.9.1.0 /hrtc/apps/mpi/openmpi/x86_64/centos8/4.1.4/gcc/8.5.0/lib/libmpi.so /shared/data1/Projects/ixdev/msekachev/geos/thirdPartyLibs/install-rdhpc8-CPU-debug/suitesparse/lib/libumfpack.so /shared/data1/Projects/ixdev/msekachev/geos/thirdPartyLibs/install-rdhpc8-CPU-debug/superlu_dist/lib64/libsuperlu_dist.so /shared/data1/Projects/ixdev/msekachev/geos/thirdPartyLibs/install-rdhpc8-CPU-debug/vtk/lib/libvtkIOXML-9.1.so.9.1.0 /shared/data1/Projects/ixdev/msekachev/geos/thirdPartyLibs/install-rdhpc8-CPU-debug/vtk/lib/libvtkIOXMLParser-9.1.so.9.1.0 /shared/data1/Projects/ixdev/msekachev/geos/thirdPartyLibs/install-rdhpc8-CPU-debug/vtk/lib/libvtkIOCore-9.1.so.9.1.0 /shared/data1/Projects/ixdev/msekachev/geos/thirdPartyLibs/install-rdhpc8-CPU-debug/vtk/lib/libvtkCommonExecutionModel-9.1.so.9.1.0 /shared/data1/Projects/ixdev/msekachev/geos/thirdPartyLibs/install-rdhpc8-CPU-debug/vtk/lib/libvtkCommonDataModel-9.1.so.9.1.0 /shared/data1/Projects/ixdev/msekachev/geos/thirdPartyLibs/install-rdhpc8-CPU-debug/vtk/lib/libvtkCommonTransforms-9.1.so.9.1.0 /shared/data1/Projects/ixdev/msekachev/geos/thirdPartyLibs/install-rdhpc8-CPU-debug/vtk/lib/libvtkCommonMisc-9.1.so.9.1.0 /shared/data1/Projects/ixdev/msekachev/geos/thirdPartyLibs/install-rdhpc8-CPU-debug/vtk/lib/libvtkCommonMath-9.1.so.9.1.0 /shared/data1/Projects/ixdev/msekachev/geos/thirdPartyLibs/install-rdhpc8-CPU-debug/vtk/lib/libvtkkissfft-9.1.so.9.1.0 /shared/data1/Projects/ixdev/msekachev/geos/thirdPartyLibs/install-rdhpc8-CPU-debug/vtk/lib/libvtkCommonSystem-9.1.so.9.1.0 /shared/data1/Projects/ixdev/msekachev/geos/thirdPartyLibs/install-rdhpc8-CPU-debug/vtk/lib/libvtkCommonCore-9.1.so.9.1.0 -pthread /shared/data1/Projects/ixdev/msekachev/geos/thirdPartyLibs/install-rdhpc8-CPU-debug/vtk/lib/libvtksys-9.1.so.9.1.0 -ldl -Wl,-rpath-link,/shared/data1/Projects/ixdev/msekachev/geos/thirdPartyLibs/install-rdhpc8-CPU-debug/vtk/lib 
lib/libgeosx_core.so: undefined reference to `grpc_channel_create'
```

**Comment by bmhan12** [comment]
A few suggestions I have:

- Create a simple smoke test to verify the grpc dependency is found and working.
  - You can find a smoke test I created for caliper in [testCaliperSmoke.cpp](https://github.com/GEOS-DEV/GEOS/blob/develop/src/coreComponents/common/unitTests/testCaliperSmoke.cpp). You can modify common's CMakeLists.txt so that it can temporarily depend on your new library for testing. This should speedup the debugging process, and I think a smoke test would be useful for GEOS.
  - This smoke test was based on blt's suite of smoke tests, which you can find here: https://github.com/LLNL/blt/tree/develop/tests/smoke
- Use `blt_print_target_properties` for debugging: https://llnl-blt.readthedocs.io/en/develop/api/target_properties.html#blt-print-target-properties
  - You can read blt's documentation on how to finely control the output, but calling the CMake macro with the `events`/`geosx`/`grpc`/`grpc::grpc`/etc CMake targets will provide debugging information (headers, dependencies, etc.)
  


> In the commit above, please note that I had to use find_package() for several other packages before the final find_package(gRPC) would execute correctly. I also used the following parameters in set_property() call...

Is it possible that these packages are dependencies of gRPC, and maybe it matters what order they appear when linking, similar to hypre here? : https://github.com/GEOS-DEV/GEOS/blob/69727912de203077e83ba20a0cd724f785e7136d/src/cmake/thirdparty/SetupGeosxThirdParty.cmake#L668-L681

**Comment by MichaelSekachev** [comment]
> A few suggestions I have:
> 
> * Create a simple smoke test to verify the grpc dependency is found and working.
>   
>   * You can find a smoke test I created for caliper in [testCaliperSmoke.cpp](https://github.com/GEOS-DEV/GEOS/blob/develop/src/coreComponents/common/unitTests/testCaliperSmoke.cpp). You can modify common's CMakeLists.txt so that it can temporarily depend on your new library for testing. This should speedup the debugging process, and I think a smoke test would be useful for GEOS.
>   * This smoke test was based on blt's suite of smoke tests, which you can find here: https://github.com/LLNL/blt/tree/develop/tests/smoke
> * Use `blt_print_target_properties` for debugging: https://llnl-blt.readthedocs.io/en/develop/api/target_properties.html#blt-print-target-properties
>   
>   * You can read blt's documentation on how to finely control the output, but calling the CMake macro with the `events`/`geosx`/`grpc`/`grpc::grpc`/etc CMake targets will provide debugging information (headers, dependencies, etc.)
> 
> > In the commit above, please note that I had to use find_package() for several other packages before the final find_package(gRPC) would execute correctly. I also used the following parameters in set_property() call...
> 
> Is it possible that these packages are dependencies of gRPC, and maybe it matters what order they appear when linking, similar to hypre here? :
> 
> https://github.com/GEOS-DEV/GEOS/blob/69727912de203077e83ba20a0cd724f785e7136d/src/cmake/thirdparty/SetupGeosxThirdParty.cmake#L668-L681

Hi Brian. Thank you for leaving the comments. In fact, I just realized that linking against libgrpc.a is not what I was supposed to do. The correct library name is libgrpc++.a :exploding_head:. So basically I had to change gRPC::grpc to gRPC::grpc++ everywhere. Now the code builds fine and I automatically get both paths passed to the linker, i.e. thirdPartyLibs/install-rdhpc8-CPU-debug/grpc/lib/libgrpc++.a followed by thirdPartyLibs/install-rdhpc8-CPU-debug/grpc/lib/libgrpc.a.

**Pull request closed without merging**
