### PR TITLE
documentation for VTKWell

### PR DESCRIPTION
**Pull request by untereiner**

### CODE REVIEW

**Comment by untereiner** [comment]
@TotoGaz, @herve-gross not sure where I should put this example deck ? In `inputFiles` and in `integratedTests` ? I do not know how to proceed for the last one.

**Review by herve-gross — APPROVED** [review]

**Comment by untereiner** [comment]
@herve-gross I made some modifications. Instead of adding a whole new example I modified the existing one from the tutorial. I added the vtk files here https://github.com/GEOS-DEV/GEOSDATA/pull/1

**Comment by untereiner** [comment]
@herve-gross do you have the rights to merge ? Could you have a look to https://github.com/GEOS-DEV/GEOSDATA/pull/1

**Comment by herve-gross** [comment]
> @herve-gross do you have the rights to merge ? Could you have a look to [GEOS-DEV/GEOSDATA#1](https://github.com/GEOS-DEV/GEOSDATA/pull/1)

I do not have merge rights, no. Let me first review your PR, and then we will pass it on to @TotoGaz for the merge management.

**Review by herve-gross — APPROVED** [review]
Thanks for the clear documentation work.

**Comment by paveltomin** [comment]
merge queue?

**Pull request merged**
