### PR TITLE
Python Packaging Updates

### PR DESCRIPTION
**Pull request by untereiner**
Associated geosPythonPackages PR: https://github.com/GEOS-DEV/geosPythonPackages/pull/13

### CODE REVIEW

**Comment by cssherman** [comment]
@untereiner - It looks like we'll need to update some import names in the integrated tests.  I'll give this a shot and see how if the CI integrated tests step passes.

**Comment by untereiner** [comment]
@cssherman there are integrated tested that are failing.. is it ok ?

**Review by cssherman — APPROVED** [review]
OK, this looks good to go now.  Let's add it to the merge queue

**Comment by cssherman** [comment]
Note:  Before merging this branch, we need to do 1) Merge the changes in the linked geosPythonPackages branch, 2) Remove the temporary branch name in the cmake, and 3) Re-run the tests

**Pull request merged**
