### PR TITLE
fix: bugfix about norm vector size

### PR DESCRIPTION
**Pull request by paveltomin**
many thanks to @tjb-ltk for finding it

### CODE REVIEW

**Comment by paveltomin** [comment]
@CusiniM and/or @ryar9534 let's merge this please

**Comment by ryar9534** [comment]
Was the error just that `globalResidualNorm` was scoped incorrectly?

**Review by ryar9534 — APPROVED** [review]

**Comment by paveltomin** [comment]
> Was the error just that `globalResidualNorm` was scoped incorrectly?

yes, local and global had different sizes but MPI function was not aware of that leading to wrong memory access

**Review by rrsettgast — APPROVED** [review]

**Review by CusiniM — APPROVED** [review]

**Comment by CusiniM** [comment]
I have https://github.com/GEOS-DEV/GEOS/pull/3446 that should prevent similar errors from happening.

**Pull request merged**
