### PR TITLE
docs: update publications

### PR DESCRIPTION
**Pull request by jhuang2601**
Add a recent publication on poromechanical wellbore model to the publications list

### CODE REVIEW

**Comment by ryar9534** [comment]
@jhuang2601 Do you mind if i throw my paper into this pr as well?

**Comment by jhuang2601** [comment]
> @jhuang2601 Do you mind if i throw my paper into this pr as well?

@ryar9534 Please add them in this PR.

**Review by paveltomin — APPROVED** [review]

**Comment by castelletto1** [comment]
The following paper should be moved to the 2023 group:

_Validation and Application of a Three-Dimensional Model for Simulating Proppant Transport and Fracture Conductivity_

(Rock Mechanics and Rock Engineering, Volume 56, pages 7091–7113, (2023))

**Review by castelletto1 — APPROVED** [review]

**Comment by castelletto1** [comment]
I found additional papers that should be added by looking at Francois' Google Scholar page. Should we include them in this PR?

**Comment by jhuang2601** [comment]
> I found additional papers that should be added by looking at Francois' Google Scholar page. Should we include them in this PR?

Why not. Can you suggest which should be added?

**Comment by castelletto1** [comment]
> > I found additional papers that should be added by looking at Francois' Google Scholar page. Should we include them in this PR?
> 
> Why not. Can you suggest which should be added?

OK, let me add them right now

**Review by rrsettgast — APPROVED** [review]

**Pull request merged**
