### PR TITLE
acoustic - elastic coupling (SEM, 2ⁿᵈ order wave equation)

### PR DESCRIPTION
**Pull request by tbeltzun**
This PR add a acoustic - elastic coupled SEM solver for the second order wave equation.

IntegratedTests PR: https://github.com/GEOS-DEV/integratedTests/pull/74 

PRs required:
- https://github.com/GEOS-DEV/GEOS/pull/2548: required for the coupling terms;
- https://github.com/GEOS-DEV/GEOS/pull/2642: high order ricker wavelets;
- https://github.com/GEOS-DEV/GEOS/pull/2641: `--output` cli flag fix;
- https://github.com/GEOS-DEV/GEOS/pull/2722;
- https://github.com/GEOS-DEV/GEOS/pull/2718;
- https://github.com/GEOS-DEV/GEOS/pull/2729;
- https://github.com/GEOS-DEV/GEOS/pull/2730;
- https://github.com/GEOS-DEV/GEOS/pull/2818.

Optional PRs:
- https://github.com/GEOS-DEV/GEOS/pull/2723;
- https://github.com/GEOS-DEV/GEOS/pull/2721.

Linked issues:
- https://github.com/GEOS-DEV/GEOS/issues/2592: high order solution visualization (nodes and elements);
- https://github.com/GEOS-DEV/GEOS/issues/166: a workaround using node sets is currently used.

- [x] normals signs
- [x] test slanted interface, domain swap and arbitrary quadrangles under an affine transformation (not just cubes)
- [x] validate against `gar6more3d`
- [ ] investigate the following
```
VTKOutput: Warning! 1 field name specified in `fieldNames` is/are not registered anywhere.
VTKOutput: Warning! `pressure_np1` is not registered anywhere and will not be displayed.
```

Rename generic fields such as `mediumVelocity` to `acousticVelocity` to allow coupling solvers (namespace conflict).

### CODE REVIEW

**Comment by tbeltzun** [comment]
Validation run against [gar6more3d](https://gitlab.inria.fr/jdiaz/gar6more3d):

Acoustic receivers:
```
4 infinite medium (1), free surface (2), wall boundary (3) or bilayered medium(4)
0 first layer : acoustic (0) elastodynamic (1), poroelastic (2)
4 Source derivative (Hermite functions derivative, i.e. 2 for a ricker source)
10. Central frequency of the source 
1020. Amplitude of the source (× ρᶠ ?)
0.115 Delay of the source
500. Height of the source
533.3333 Height of the line of receivers (relative to interface)
2177.2936 Abscissa of the first receiver (relative to source)
0. Ordinate of the first receiver (relative to source)
2177.2936 Abscissa of the last receiver
0. Ordinate of the last receiver
1 Numbers of receivers
0. Start time
3. Stop time
1e-3 Time step (of the seismo samples)
1000 Number of intervals for the numerical computation of the convolution
1000 Number of intervals for the numerical computation of the space integration
2.295e9 1020. λᶠ and ρᶠ
1 second layer : acoustic (0) elastodynamic (1), poroelastic (2)
9.6334225e9 9.633155e9 2500. μˢ, λˢ and ρˢ
```

Elastic receivers:
```
4 infinite medium (1), free surface (2), wall boundary (3) or bilayered medium(4)
0 first layer : acoustic (0) elastodynamic (1), poroelastic (2)
4 Source derivative (Hermite functions derivative, i.e. 2 for a ricker source)
10. Central frequency of the source 
1020. Amplitude of the source (× ρᶠ ?)
0.115 Delay of the source
500. Height of the source
-533.3333 Height of the line of receivers (relative to interface)
2177.2936 Abscissa of the first receiver (relative to source)
0. Ordinate of the first receiver (relative to source)
2177.2936 Abscissa of the last receiver
0. Ordinate of the last receiver
1 Numbers of receivers
0. Start time
3. Stop time
1e-3 Time step (of the seismo samples)
500 Number of intervals for the numerical computation of the convolution
500 Number of intervals for the numerical computation of the space integration
2.295e9 1020. λᶠ and ρᶠ
1 second layer : acoustic (0) elastodynamic (1), poroelastic (2)
9.6334225e9 9.633155e9 2500. μˢ, λˢ and ρˢ
```

2023-09-26-acouselas3D-ricker3

**Comment by tbeltzun** [comment]
@acitrain, validation run from today:

2023-12-12-acouselas3D-ricker3

**Review by acitrain — APPROVED** [review]

**Comment by TotoGaz** [comment]
Hello @tbeltzun.
It looks like your `integratedTests` submodule is still stuck to [490987a](https://github.com/GEOS-DEV/integratedTests/commit/490987ae0c4f2c0b25a889766d2f1060ffd7ace8).
In the logs of the integrated tests, I can see that your PR is modifying tests like `SSLE-sedov_01` or `10x5x15Wedges_LaplaceVEM_smoke_01 `, which does not sound legitimate w.r.t. your patch.
Can you double check please?

**Comment by tbeltzun** [comment]
> Can you double check please?

Again, sorry, git submodules issues. Fixed.

**Comment by tbeltzun** [comment]
We had an `integratedTests` regression on `Quartz`, which is fixed by https://github.com/GEOS-DEV/GEOS/pull/2813/commits/e771fe64eabbafcc42cfb97b79f969913e0c4ce9 (`m_coarseningRatio` un-initialized).

With the fixed and updated rebaseline, this PR is now ready to be merged.

**Review by sframba — APPROVED** [review]

**Pull request merged**
