### PR TITLE
fix blas lapack links for tests

### PR DESCRIPTION
**Pull request by herve-gross**
This fixes my linker errors (Blas and Lapack symbols not found for arm64 architecture) on these two sets of unit tests.

### CODE REVIEW

**Review by CusiniM — APPROVED** [review]

**Comment by paveltomin** [comment]
@herve-gross abandon?

**Comment by herve-gross** [comment]
this should be an easy merge

**Comment by rrsettgast** [comment]
Is this needed anymore?

**Comment by herve-gross** [comment]
for me, yes

**Pull request merged**
