### PR TITLE
Feature: Allow negative pressure 

### PR DESCRIPTION
**Pull request by untereiner**

### CODE REVIEW

**Comment by untereiner** [comment]
@dkachuma can this PR be reviewed as it is ? Should it be converted to a draft ?

**Comment by dkachuma** [comment]
> @dkachuma can this PR be reviewed as it is ? Should it be converted to a draft ?
I'm not sure about merging this. I think we need to have a discussion about the merits and dangers of allowing negative pressures with the wider community. i think this should be set to draft for now until we get more views/thoughts.

Have you verified that the change fixes the issue with the target model?

**Comment by untereiner** [comment]
> Have you verified that the change fixes the issue with the target model?

Yes it does !

**Comment by untereiner** [comment]
Hello @dkachuma, what about this PR ? Should it be made up to date ? closed ?

**Comment by paveltomin** [comment]
negative pressure is allowed by default for single phase and can be disabled with an option when needed
having negative pressure in compositional is not a good sign and should be avoided at all cost imho

**Pull request closed without merging**
