### PR TITLE
Revert target region check accidentally commented in #2568

### PR DESCRIPTION
**Pull request by paveltomin**
Bring back the check (was commented in https://github.com/GEOS-DEV/GEOS/pull/2568) and correct the inputs accordingly.
No results change but needs rebaselines because some of some mechanics wrappers not anymore present for wells.

https://github.com/GEOS-DEV/integratedTests/pull/76

### CODE REVIEW

**Review by castelletto1 — APPROVED** [review]
👍

**Comment by TotoGaz** [comment]
Hi @paveltomin , this is now on top of the merge queue.
Do you want to push your `integratedTests` PR or would you prefer me to do it?

**Comment by paveltomin** [comment]
> Hi @paveltomin , this is now on top of the merge queue. Do you want to push your `integratedTests` PR or would you prefer me to do it?

will do everything myself, thank you

**Comment by TotoGaz** [comment]
> will do everything myself, thank you

Ok, ping me for the final check 😉

**Comment by TotoGaz** [comment]
@paveltomin This PR is on top of the merge queue. Can you manage the conflict so we can try to merge it?

**Comment by paveltomin** [comment]
> @paveltomin This PR is on top of the merge queue. Can you manage the conflict so we can try to merge it?

fixing it right now

**Pull request merged**
