### PR TITLE
Small improvement for xml error message

### PR DESCRIPTION
**Pull request by paveltomin**
Small improvement for xml error message: print also attribute name

### CODE REVIEW

**Comment by TotoGaz** [comment]
@MelReyCG Can you have a look at this PR which improves the error messages like you're currently working on!

**Comment by MelReyCG** [comment]
Hi @paveltomin 
I'm working on a PR that - I think - includes the feature you're proposing here: #2404 
In this PR, the following information will be added to the thrown exceptions from `stringToInputVariable()`:
- Group name
- Attribute name
- xml file & line where the attribute has been declared.
If you would like to see this P.R. in detail, these exceptions are caught in `Wrapper::processInputFile()`, and formatted in `WrapperBase::processInputException()`.

**Comment by paveltomin** [comment]
Yeah, @MelReyCG's PR goes above and beyond, great work!
How long do you think it will take to merge it?

**Comment by TotoGaz** [comment]
@MelReyCG Does your PR completely embraces @paveltomin's improvements?
What do you think will be most efficient way to merge those patches?

**Comment by MelReyCG** [comment]
@TotoGaz Yes, my PR completely includes the improvements that @paveltomin is proposing here.

 

I can show you an example of output. Imagine an user is doubling a dot in a decimal value in the following block:
```
<Perforation
        name="injector1_perf1"
        distanceFromHead="45..0"/>
```

 

Here was the original output where there was no mention of the error source:
```
***** LOCATION: /appli_PITSI/MelvinRey/GEOSX_repos/GEOSX/src/coreComponents/dataRepository/xmlWrapper.hpp:125
***** Controlling expression (should be false): ss.fail() || !ss.eof()
***** Rank 0: Error detected while parsing string: "45..0"
```

 

And as you can see below on the output of the PR #2404, the node and attribute names are mentioned in the first error line, followed by the file and line:
```
***** XML parsing error at node named injector1_perf1, attribute distanceFromHead (simpleCo2Inj_smoke.xml, l.34).
***** Input value: '45..0'
***** LOCATION: /appli_PITSI/MelvinRey/GEOSX_repos/GEOSX_line2/src/coreComponents/dataRepository/xmlWrapper.hpp:293
***** Controlling expression (should be false): ss.fail() || !ss.eof()
***** Rank 0: Error detected while parsing string: "45..0"

```

@paveltomin If you want to try my full work on error messages, it's all included in my branch named `feature/rey/xml-error-line-wip`

**Comment by TotoGaz** [comment]
@paveltomin What do you think? Should we wait for @MelReyCG 's PR to get merged in order to avoid conflicts? The PRs are nearly ready. BTW, you're more than welcome to review the code: your XP on the subject can be very useful.

**Comment by paveltomin** [comment]
I am closing this PR with hope that @MelReyCG 's PRs will be merged soon.
They look great to me and I don't have any additional suggestions.

**Pull request closed without merging**
