### PR TITLE
Install both `geosx` and `geos` executables.

### PR DESCRIPTION
**Pull request by TotoGaz**
Both `geosx` and `geos` will be available in the installation folder, in order to let the end users adapt their scripts.
Only the `geosx` executable is built in the build folder.

Relates to https://github.com/GEOS-DEV/GEOS/issues/2331

### CODE REVIEW

**Comment by TotoGaz** [comment]
@rrsettgast what do you think of this patch?

**Review by rrsettgast — CHANGES_REQUESTED** [review]
Perhaps update documentation at this point?

**Review by rrsettgast — APPROVED** [review]
just commit it, and make an issue to follow up the deprecation messages, and the documentation if you wish.

**Comment by TotoGaz** [comment]
I've just added the appropriate entry to https://github.com/GEOS-DEV/GEOS/issues/2331

**Pull request merged**
