### PR TITLE
Add variable density inside second order acoustic wave solver

### PR DESCRIPTION
**Pull request by acitrain**
This PR add the possibility of using variable cell-wise density for the second order acoustic wave solver.

### CODE REVIEW

**Review by sframba — APPROVED** [review]

**Comment by rrsettgast** [comment]
@acitrain Do you have an integratedTests rebaseline PR ready for this?

**Comment by acitrain** [comment]
> @acitrain Do you have an integratedTests rebaseline PR ready for this?

Hi @rrsettgast,

No not yet, it still vacation for some of us here and I do not have the key to access Quartz...

**Comment by sframba** [comment]
I'll do the integratedTests PR today, should be ready soon

**Comment by sframba** [comment]
Intgrated tests PR: [#34](https://github.com/GEOS-DEV/integratedTests/pull/34)

**Comment by CusiniM** [comment]
Just need to press merge once the CI is done.

**Pull request merged**
