### PR TITLE
RAJA `loop_exec` deprecated for `seq_exec`

### PR DESCRIPTION
**Pull request by wrtobin**
Current RAJA development head has dropped `loop_exec` fully, in order to maintain compatibility we need to switch to `seq_exec`.

`seq_exec` has been present for several major versions IIRC, so this shouldn't break anyone's build unless they're using an already outdated version of RAJA.

### CODE REVIEW

**Comment by wrtobin** [comment]
https://github.com/GEOS-DEV/LvArray/pull/309

**Review by rrsettgast — APPROVED** [review]

**Comment by TotoGaz** [comment]
Is this PR requiring rebaseline?

**Comment by wrtobin** [comment]
It shouldn't, its effectively just a symbol name change in raja and the loop execution order (and any resulting operation ordering) should be identical.

**Comment by wrtobin** [comment]
It is possible someone might encounter a build failure if they're using an old version of raja, but it would have to be over a year old and that should be considered well out of date.

**Comment by TotoGaz** [comment]
> It shouldn't, its effectively just a symbol name change in raja and the loop execution order (and any resulting operation ordering) should be identical.

Then let's add the `ci: run integrated tests` before, then we know and we can get to the merge queue! 😉

**Comment by TotoGaz** [comment]
> It is possible someone might encounter a build failure if they're using an old version of raja, but it would have to be over a year old and that should be considered well out of date.

We precise which version of `raja` we need since we link to the `TPL` explicitly: it's not really our responsibility!

**Comment by wrtobin** [comment]
> > It is possible someone might encounter a build failure if they're using an old version of raja, but it would have to be over a year old and that should be considered well out of date.
> 
> We precise which version of `raja` we need since we link to the `TPL` explicitly: it's not really our responsibility!

I just double-checked and `seq_exec` has been present in raja for 6 years. `loop_exec` is deprecated, removed in the current `develop` head but not in any releases yet, the next release will include dropping it completely.

**Comment by TotoGaz** [comment]
```
    Status     : TestCase                              : Directory                                                 : Elapsed : Resources : TestStep  
    ---------- : ------------------------------------- : --------------------------------------------------------- : ------- : --------- : ----------
    FAIL CHECK : PoroElastic_permeableFault_smoke_01   : poroElasticCoupling/PoroElastic_permeableFault_smoke_01   : 0:00:05 : 0:00:05   : restartcheck
    FAIL CHECK : PoroElastic_impermeableFault_smoke_01 : poroElasticCoupling/PoroElastic_impermeableFault_smoke_01 : 0:00:05 : 0:00:05   : restartcheck
    ---------- : ------------------------------------- : --------------------------------------------------------- : ------- : --------- : ----------
```
does not require rebaseline.

**Review by CusiniM — APPROVED** [review]

**Pull request merged**
