### PR TITLE
remove RESQML support from GEOS

### PR DESCRIPTION
**Pull request by untereiner**
Companion PR https://github.com/GEOS-DEV/thirdPartyLibs/pull/258

### CODE REVIEW

**Comment by untereiner** [comment]
@TotoGaz I don't know how to deal with the spack recipes.  Should I remove them too ? They could be necessary for building geos with spack with the RESQML external component

**Comment by bmhan12** [comment]
@untereiner I can remove them from spack if they are no longer being used.

**Comment by TotoGaz** [comment]
That would be nice, thank you @bmhan12 
@untereiner does it make sense to keep the `spack` recipe if we're not using/validating it anymore? Is the `git` history enough if we want to revive it?

**Comment by untereiner** [comment]
Thank you @bmhan12 ! If think the git history is enough. I am wondering how to play with these recipes with what I call an « external component » eg: added at compile time but in another repository

**Comment by TotoGaz** [comment]
> I am wondering how to play with these recipes with what I call an « external component » eg: added at compile time but in another repository

You mean `spack` recipes? I've never been using `spack` so I do not know.

**Comment by untereiner** [comment]
Yes, I ment spack recipes.

**Comment by untereiner** [comment]
@TotoGaz This one should be easy

**Review by TotoGaz — APPROVED** [review]

**Pull request merged**
